# FILE: prefect.yaml
# PURPOSE: Prefect deployment configuration for Agency OS
# PHASE: 5 (Orchestration)
# TASK: ORC-011
# DEPENDENCIES:
#   - Dockerfile.prefect
#   - src/orchestration/flows/*.py
# RULES APPLIED:
#   - Rule 1: Follow blueprint exactly
#   - Rule 20: Webhook-first architecture - cron jobs are safety nets
#   - Prefect 3.x deployment patterns

# Prefect project configuration
name: agency-os
prefect-version: 3.0.0

# Build/push steps removed - Railway handles container building
# Worker container is built via Dockerfile.worker

# Pull configuration for workers (set working directory)
pull:
  - prefect.deployments.steps.set_working_directory:
      directory: /app

# Deployment definitions
# NOTE: Scheduled flows PAUSED, webhook flows ACTIVE for on-demand/testing
deployments:
  # ============================================
  # CAMPAIGN FLOWS
  # ============================================

  # Campaign activation flow (webhook-triggered)
  - name: campaign-flow
    version: 1.0.0
    paused: false  # Webhook - active for on-demand triggers
    tags: [campaign, activation, webhook-triggered]
    description: "Campaign activation and validation flow (webhook-triggered)"
    entrypoint: src/orchestration/flows/campaign_flow.py:campaign_activation_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # ============================================
  # ENRICHMENT FLOWS
  # ============================================

  # Daily enrichment flow (safety net)
  - name: enrichment-flow
    version: 1.0.0
    paused: true
    tags: [enrichment, daily, safety-net]
    description: "Daily enrichment safety net at 2 AM AEST"
    entrypoint: src/orchestration/flows/enrichment_flow.py:daily_enrichment_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    parameters:
      batch_size: 100
    schedules:
      - cron: "0 2 * * *"
        timezone: Australia/Sydney
        active: false

  # ============================================
  # OUTREACH FLOWS
  # ============================================

  # Hourly outreach flow (business hours safety net)
  - name: outreach-flow
    version: 1.0.0
    paused: true
    tags: [outreach, hourly, business-hours, safety-net]
    description: "Hourly outreach during business hours (8 AM-6 PM AEST, Mon-Fri)"
    entrypoint: src/orchestration/flows/outreach_flow.py:hourly_outreach_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    parameters:
      batch_size: 50
    schedules:
      - cron: "0 8-18 * * 1-5"
        timezone: Australia/Sydney
        active: false

  # Reply recovery flow (6-hourly safety net)
  - name: reply-recovery-flow
    version: 1.0.0
    paused: true
    tags: [replies, recovery, safety-net]
    description: "Reply recovery safety net every 6 hours"
    entrypoint: src/orchestration/flows/reply_recovery_flow.py:reply_recovery_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    parameters:
      lookback_hours: 6
    schedules:
      - interval: 21600
        timezone: Australia/Sydney
        active: false

  # ============================================
  # ONBOARDING FLOWS
  # ============================================

  # ICP onboarding flow (webhook-triggered for new clients)
  - name: onboarding-flow
    version: 1.0.0
    paused: false  # Webhook - active for on-demand triggers
    tags: [onboarding, icp, webhook-triggered]
    description: "ICP extraction and onboarding for new clients"
    entrypoint: src/orchestration/flows/onboarding_flow.py:icp_onboarding_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # ICP re-extract flow (webhook-triggered)
  - name: icp-reextract-flow
    version: 1.0.0
    paused: false  # Webhook - active for on-demand triggers
    tags: [onboarding, icp, reextract, webhook-triggered]
    description: "Re-extract ICP for existing client"
    entrypoint: src/orchestration/flows/onboarding_flow.py:icp_reextract_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # ============================================
  # LEAD POOL FLOWS
  # ============================================

  # Pool population flow (webhook-triggered)
  - name: pool-population-flow
    version: 1.0.0
    paused: false  # Webhook - active for on-demand triggers
    tags: [pool, population, webhook-triggered]
    description: "Populate lead pool with enriched leads"
    entrypoint: src/orchestration/flows/pool_population_flow.py:pool_population_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # Pool campaign assignment flow (webhook-triggered)
  - name: pool-assignment-flow
    version: 1.0.0
    paused: false  # Webhook - active for on-demand triggers
    tags: [pool, assignment, webhook-triggered]
    description: "Assign leads from pool to campaign"
    entrypoint: src/orchestration/flows/pool_assignment_flow.py:pool_campaign_assignment_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # Pool daily allocation flow (scheduled)
  - name: pool-daily-allocation-flow
    version: 1.0.0
    paused: true
    tags: [pool, allocation, daily, safety-net]
    description: "Daily lead allocation from pools to campaigns at 6 AM AEST"
    entrypoint: src/orchestration/flows/pool_assignment_flow.py:pool_daily_allocation_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules:
      - cron: "0 6 * * *"
        timezone: Australia/Sydney
        active: false

  # ============================================
  # BILLING/CREDIT FLOWS
  # ============================================

  # Credit reset check flow (hourly safety net)
  - name: credit-reset-flow
    version: 1.0.0
    paused: false  # Critical billing flow - active
    tags: [billing, credits, hourly, critical]
    description: "Hourly credit reset check for billing integrity"
    entrypoint: src/orchestration/flows/credit_reset_flow.py:credit_reset_check_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules:
      - cron: "0 * * * *"
        timezone: Australia/Sydney
        active: false

  # Monthly replenishment flow (triggered by credit reset)
  - name: monthly-replenishment-flow
    version: 1.0.0
    paused: false  # Triggered by credit_reset - active
    tags: [leads, monthly, replenishment]
    description: "Post-credit-reset lead replenishment (triggered, not scheduled)"
    entrypoint: src/orchestration/flows/monthly_replenishment_flow.py:monthly_replenishment_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # ============================================
  # CAMPAIGN EVOLUTION FLOWS
  # ============================================

  # Campaign evolution flow (triggered after pattern learning)
  - name: campaign-evolution-flow
    version: 1.0.0
    paused: false  # Triggered by pattern_learning - active
    tags: [campaigns, evolution, cis, suggestions]
    description: "CIS-driven campaign optimization suggestions (triggered, not scheduled)"
    entrypoint: src/orchestration/flows/campaign_evolution_flow.py:campaign_evolution_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # Batch campaign evolution (all eligible clients)
  - name: batch-campaign-evolution-flow
    version: 1.0.0
    paused: false  # Triggered after weekly pattern learning
    tags: [campaigns, evolution, batch]
    description: "Run campaign evolution for all eligible clients"
    entrypoint: src/orchestration/flows/campaign_evolution_flow.py:batch_campaign_evolution_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # ============================================
  # CRM SYNC FLOWS (Item 20)
  # ============================================

  # CRM sync flow (6-hourly safety net for missed webhooks)
  - name: crm-sync-flow
    version: 1.0.0
    paused: true  # Safety net - enable when CRMs configured
    tags: [crm, sync, safety-net, blind-conversions]
    description: "CRM sync every 6 hours - safety net for missed webhooks (blind conversions)"
    entrypoint: src/orchestration/flows/crm_sync_flow.py:crm_sync_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    parameters:
      since_hours: 24
    schedules:
      - interval: 21600
        timezone: Australia/Sydney
        active: false

  # ============================================
  # INTELLIGENCE FLOWS
  # ============================================

  # Intelligence research flow (webhook-triggered)
  - name: intelligence-flow
    version: 1.0.0
    paused: false  # Webhook - active for on-demand triggers
    tags: [intelligence, research, webhook-triggered]
    description: "Deep research on lead for conversion intelligence"
    entrypoint: src/orchestration/flows/intelligence_flow.py:intelligence_research_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # Lead research trigger flow (webhook-triggered)
  - name: trigger-lead-research
    version: 1.0.0
    paused: false  # Webhook - active for on-demand triggers
    tags: [intelligence, lead-research, webhook-triggered]
    description: "Trigger research for individual lead"
    entrypoint: src/orchestration/flows/intelligence_flow.py:trigger_lead_research_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # ============================================
  # PATTERN LEARNING FLOWS
  # ============================================

  # Weekly pattern learning flow (scheduled)
  - name: pattern-learning-flow
    version: 1.0.0
    paused: true
    tags: [patterns, learning, weekly]
    description: "Weekly pattern learning at 3 AM Sunday AEST"
    entrypoint: src/orchestration/flows/pattern_learning_flow.py:weekly_pattern_learning_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules:
      - cron: "0 3 * * 0"
        timezone: Australia/Sydney
        active: false

  # Single client pattern learning (webhook-triggered)
  - name: client-pattern-learning-flow
    version: 1.0.0
    paused: false  # Webhook - active for on-demand triggers
    tags: [patterns, learning, webhook-triggered]
    description: "Pattern learning for single client"
    entrypoint: src/orchestration/flows/pattern_learning_flow.py:single_client_pattern_learning_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # Pattern backfill flow (manual/one-time)
  - name: pattern-backfill-flow
    version: 1.0.0
    paused: false  # Manual - active for on-demand triggers
    tags: [patterns, backfill, manual]
    description: "Backfill historical patterns (manual trigger)"
    entrypoint: src/orchestration/flows/pattern_backfill_flow.py:pattern_backfill_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

  # Single client backfill flow (webhook-triggered)
  - name: client-backfill-flow
    version: 1.0.0
    paused: false  # Webhook - active for on-demand triggers
    tags: [patterns, backfill, webhook-triggered]
    description: "Backfill patterns for single client"
    entrypoint: src/orchestration/flows/pattern_backfill_flow.py:single_client_backfill_flow
    work_pool:
      name: agency-os-pool
      work_queue_name: agency-os-queue
    schedules: []

# Environment variables reference
# These should be set in Railway/environment, not hardcoded here
# Required environment variables:
# - DATABASE_URL
# - REDIS_URL
# - ANTHROPIC_API_KEY
# - APOLLO_API_KEY
# - APIFY_API_KEY
# - CLAY_API_KEY
# - RESEND_API_KEY
# - TWILIO_ACCOUNT_SID
# - TWILIO_AUTH_TOKEN
# - HEYREACH_API_KEY
# - PREFECT_API_URL

# Worker configuration
# Workers pull from the agency-os-queue and execute flows
# Start worker with: prefect worker start --pool agency-os-pool

# === VERIFICATION CHECKLIST ===
# [x] Prefect 3.x syntax
# [x] 18 flows defined (all operational flows)
# [x] Work pool: agency-os-pool
# [x] Work queue: agency-os-queue
# [x] Schedules configured with Australia/Sydney timezone
# [x] All flows PAUSED until production ready
# [x] All schedules INACTIVE until production ready
# [x] Webhook-first architecture (schedules are safety nets)
# [x] No hardcoded credentials
