// Type declarations for modules without TypeScript types

declare module '@tabler/icons-react' {
  import { FC, SVGProps } from 'react';
  type IconComponent = FC<SVGProps<SVGSVGElement>>;
  
  // Export every possible icon name as IconComponent
  export const IconArrowLeft: IconComponent;
  export const IconArrowRight: IconComponent;
  export const IconArrowNarrowLeft: IconComponent;
  export const IconArrowNarrowRight: IconComponent;
  export const IconX: IconComponent;
  export const IconUpload: IconComponent;
  export const IconLayoutNavbarCollapse: IconComponent;
  export const IconBrandGithub: IconComponent;
  export const IconBrandX: IconComponent;
  export const IconExchange: IconComponent;
  export const IconHome: IconComponent;
  export const IconNewSection: IconComponent;
  export const IconTerminal2: IconComponent;
  export const IconBrandApple: IconComponent;
  export const IconSearch: IconComponent;
  export const IconWorld: IconComponent;
  export const IconCommand: IconComponent;
  export const IconCaretRightFilled: IconComponent;
  export const IconCaretDownFilled: IconComponent;
  export const IconCaretUpFilled: IconComponent;
  export const IconDotsVertical: IconComponent;
  export const IconMicrophone: IconComponent;
  export const IconChevronUp: IconComponent;
  export const IconBrightnessUp: IconComponent;
  export const IconBrightnessDown: IconComponent;
  export const IconVolume: IconComponent;
  export const IconVolume2: IconComponent;
  export const IconVolume3: IconComponent;
  export const IconTable: IconComponent;
  export const IconPlayerTrackPrev: IconComponent;
  export const IconPlayerTrackNext: IconComponent;
  export const IconPlayerSkipForward: IconComponent;
  export const IconMoon: IconComponent;
  export const IconSun: IconComponent;
  export const IconMenu: IconComponent;
  export const IconMenu2: IconComponent;
  export const IconSettings: IconComponent;
  export const IconUser: IconComponent;
  export const IconUsers: IconComponent;
  export const IconMail: IconComponent;
  export const IconBell: IconComponent;
  export const IconHeart: IconComponent;
  export const IconStar: IconComponent;
  export const IconCheck: IconComponent;
  export const IconPlus: IconComponent;
  export const IconMinus: IconComponent;
  export const IconEdit: IconComponent;
  export const IconTrash: IconComponent;
  export const IconDownload: IconComponent;
  export const IconShare: IconComponent;
  export const IconCopy: IconComponent;
  export const IconLink: IconComponent;
  export const IconExternalLink: IconComponent;
  export const IconChevronDown: IconComponent;
  export const IconChevronLeft: IconComponent;
  export const IconChevronRight: IconComponent;
  export const IconLoader: IconComponent;
  export const IconRefresh: IconComponent;
  export const IconFilter: IconComponent;
  export const IconSort: IconComponent;
  export const IconEye: IconComponent;
  export const IconEyeOff: IconComponent;
  export const IconLock: IconComponent;
  export const IconUnlock: IconComponent;
  export const IconCalendar: IconComponent;
  export const IconClock: IconComponent;
  export const IconMapPin: IconComponent;
  export const IconPhone: IconComponent;
  export const IconMessage: IconComponent;
  export const IconPhoto: IconComponent;
  export const IconVideo: IconComponent;
  export const IconFile: IconComponent;
  export const IconFolder: IconComponent;
  export const IconCloud: IconComponent;
  export const IconDatabase: IconComponent;
  export const IconCode: IconComponent;
  export const IconTerminal: IconComponent;
  export const IconBug: IconComponent;
  export const IconRocket: IconComponent;
  export const IconFlame: IconComponent;
  export const IconBolt: IconComponent;
  export const IconZap: IconComponent;
  export const IconAward: IconComponent;
  export const IconTrophy: IconComponent;
  export const IconTarget: IconComponent;
  export const IconFlag: IconComponent;
  export const IconBookmark: IconComponent;
  export const IconTag: IconComponent;
  export const IconHash: IconComponent;
  export const IconAt: IconComponent;
  export const IconDollar: IconComponent;
  export const IconPercent: IconComponent;
  export const IconChart: IconComponent;
  export const IconChartBar: IconComponent;
  export const IconChartLine: IconComponent;
  export const IconChartPie: IconComponent;
  export const IconDashboard: IconComponent;
  export const IconActivity: IconComponent;
  export const IconPulse: IconComponent;
  export const IconWifi: IconComponent;
  export const IconBluetooth: IconComponent;
  export const IconBattery: IconComponent;
  export const IconPower: IconComponent;
  export const IconCircle: IconComponent;
  export const IconSquare: IconComponent;
  export const IconTriangle: IconComponent;
  export const IconHexagon: IconComponent;
  export const IconOctagon: IconComponent;
  export const IconDiamond: IconComponent;
  export const IconCrown: IconComponent;
  export const IconShield: IconComponent;
  export const IconKey: IconComponent;
  export const IconFingerprint: IconComponent;
  export const IconScan: IconComponent;
  export const IconQrcode: IconComponent;
  export const IconBarcode: IconComponent;
  export const IconPrinter: IconComponent;
  export const IconCamera: IconComponent;
  export const IconScreenshot: IconComponent;
  export const IconMaximize: IconComponent;
  export const IconMinimize: IconComponent;
  export const IconExpand: IconComponent;
  export const IconCompress: IconComponent;
  export const IconZoomIn: IconComponent;
  export const IconZoomOut: IconComponent;
  export const IconRotate: IconComponent;
  export const IconFlip: IconComponent;
  export const IconCrop: IconComponent;
  export const IconPalette: IconComponent;
  export const IconBrush: IconComponent;
  export const IconPencil: IconComponent;
  export const IconEraser: IconComponent;
  export const IconHighlight: IconComponent;
  export const IconBold: IconComponent;
  export const IconItalic: IconComponent;
  export const IconUnderline: IconComponent;
  export const IconStrikethrough: IconComponent;
  export const IconAlignLeft: IconComponent;
  export const IconAlignCenter: IconComponent;
  export const IconAlignRight: IconComponent;
  export const IconAlignJustify: IconComponent;
  export const IconList: IconComponent;
  export const IconListOrdered: IconComponent;
  export const IconIndent: IconComponent;
  export const IconOutdent: IconComponent;
  export const IconQuote: IconComponent;
  export const IconHeading: IconComponent;
  export const IconParagraph: IconComponent;
  export const IconTextResize: IconComponent;
  export const IconTypography: IconComponent;
  export const IconLanguage: IconComponent;
  export const IconTranslate: IconComponent;
  export const IconGlobe: IconComponent;
  export const IconCompass: IconComponent;
  export const IconMap: IconComponent;
  export const IconNavigation: IconComponent;
  export const IconRoute: IconComponent;
  export const IconDirections: IconComponent;
  export const IconCar: IconComponent;
  export const IconBus: IconComponent;
  export const IconTrain: IconComponent;
  export const IconPlane: IconComponent;
  export const IconShip: IconComponent;
  export const IconBike: IconComponent;
  export const IconWalk: IconComponent;
  export const IconRun: IconComponent;
  export const IconSwim: IconComponent;
  export const IconGym: IconComponent;
  export const IconYoga: IconComponent;
  export const IconMeditation: IconComponent;
  export const IconHeart2: IconComponent;
  export const IconHeartbeat: IconComponent;
  export const IconMedical: IconComponent;
  export const IconPill: IconComponent;
  export const IconSyringe: IconComponent;
  export const IconBandage: IconComponent;
  export const IconThermometer: IconComponent;
  export const IconStethoscope: IconComponent;
  export const IconAmbulance: IconComponent;
  export const IconHospital: IconComponent;
  export const IconEmergency: IconComponent;
  export const IconFirstAid: IconComponent;
  export const IconDna: IconComponent;
  export const IconAtom: IconComponent;
  export const IconMicroscope: IconComponent;
  export const IconFlask: IconComponent;
  export const IconTestTube: IconComponent;
  export const IconBeaker: IconComponent;
  export const IconMagnet: IconComponent;
  export const IconRadiation: IconComponent;
  export const IconBiohazard: IconComponent;
  export const IconSkull: IconComponent;
  export const IconGhost: IconComponent;
  export const IconAlien: IconComponent;
  export const IconRobot: IconComponent;
  export const IconCpu: IconComponent;
  export const IconMemory: IconComponent;
  export const IconHardDrive: IconComponent;
  export const IconSsd: IconComponent;
  export const IconUsb: IconComponent;
  export const IconSdCard: IconComponent;
  export const IconSim: IconComponent;
  export const IconChip: IconComponent;
  export const IconCircuitBoard: IconComponent;
  export const IconServer: IconComponent;
  export const IconNetwork: IconComponent;
  export const IconRouter: IconComponent;
  export const IconModem: IconComponent;
  export const IconAntenna: IconComponent;
  export const IconSatellite: IconComponent;
  export const IconRadar: IconComponent;
  export const IconSignal: IconComponent;
  export const IconBroadcast: IconComponent;
  export const IconPodcast: IconComponent;
  export const IconMusicNote: IconComponent;
  export const IconMusic: IconComponent;
  export const IconHeadphones: IconComponent;
  export const IconSpeaker: IconComponent;
  export const IconVolumeOff: IconComponent;
  export const IconMute: IconComponent;
  export const IconPlay: IconComponent;
  export const IconPause: IconComponent;
  export const IconStop: IconComponent;
  export const IconRecord: IconComponent;
  export const IconRewind: IconComponent;
  export const IconFastForward: IconComponent;
  export const IconSkipBack: IconComponent;
  export const IconSkipForward: IconComponent;
  export const IconRepeat: IconComponent;
  export const IconShuffle: IconComponent;
  export const IconPlaylist: IconComponent;
  export const IconQueue: IconComponent;
  export const IconLyrics: IconComponent;
  export const IconEqualizer: IconComponent;
  export const IconWaveform: IconComponent;
  export const IconSpectrum: IconComponent;
  export const IconVinyl: IconComponent;
  export const IconCassette: IconComponent;
  export const IconCd: IconComponent;
  export const IconDvd: IconComponent;
  export const IconBluray: IconComponent;
  export const IconTv: IconComponent;
  export const IconMonitor: IconComponent;
  export const IconLaptop: IconComponent;
  export const IconDesktop: IconComponent;
  export const IconTablet: IconComponent;
  export const IconSmartphone: IconComponent;
  export const IconWatch: IconComponent;
  export const IconGlasses: IconComponent;
  export const IconVr: IconComponent;
  export const IconAr: IconComponent;
  export const IconGamepad: IconComponent;
  export const IconJoystick: IconComponent;
  export const IconController: IconComponent;
  export const IconKeyboard: IconComponent;
  export const IconMouse: IconComponent;
  export const IconTrackpad: IconComponent;
  export const IconStylus: IconComponent;
  export const IconPen: IconComponent;
  export const IconMarker: IconComponent;
  export const IconHighlighter: IconComponent;
  export const IconCrayon: IconComponent;
  export const IconPaintBucket: IconComponent;
  export const IconDroplet: IconComponent;
  export const IconDropletOff: IconComponent;
  export const IconRainbow: IconComponent;
  export const IconSunrise: IconComponent;
  export const IconSunset: IconComponent;
  export const IconMoonrise: IconComponent;
  export const IconMoonset: IconComponent;
  export const IconStars: IconComponent;
  export const IconCloud2: IconComponent;
  export const IconCloudy: IconComponent;
  export const IconRain: IconComponent;
  export const IconSnow: IconComponent;
  export const IconWind: IconComponent;
  export const IconTornado: IconComponent;
  export const IconHurricane: IconComponent;
  export const IconThunderstorm: IconComponent;
  export const IconLightning: IconComponent;
  export const IconFog: IconComponent;
  export const IconMist: IconComponent;
  export const IconHaze: IconComponent;
  export const IconSmoke: IconComponent;
  export const IconDust: IconComponent;
  export const IconSand: IconComponent;
  export const IconAsh: IconComponent;
  export const IconVolcano: IconComponent;
  export const IconEarthquake: IconComponent;
  export const IconTsunami: IconComponent;
  export const IconFlood: IconComponent;
  export const IconDrought: IconComponent;
  export const IconFire: IconComponent;
  export const IconWildfire: IconComponent;
  export const IconExtinguisher: IconComponent;
  export const IconHydrant: IconComponent;
  export const IconFiretruck: IconComponent;
  export const IconPolice: IconComponent;
  export const IconSiren: IconComponent;
  export const IconAlarm: IconComponent;
  export const IconWarning: IconComponent;
  export const IconDanger: IconComponent;
  export const IconCaution: IconComponent;
  export const IconInfo: IconComponent;
  export const IconHelp: IconComponent;
  export const IconQuestion: IconComponent;
  export const IconQuestionMark: IconComponent;
  export const IconExclamation: IconComponent;
  export const IconExclamationMark: IconComponent;
  export const IconBan: IconComponent;
  export const IconBlock: IconComponent;
  export const IconCancel: IconComponent;
  export const IconClose: IconComponent;
  export const IconXCircle: IconComponent;
  export const IconCheckCircle: IconComponent;
  export const IconPlusCircle: IconComponent;
  export const IconMinusCircle: IconComponent;
  export const IconInfoCircle: IconComponent;
  export const IconAlertCircle: IconComponent;
  export const IconHelpCircle: IconComponent;
  export const IconArrowUp: IconComponent;
  export const IconArrowDown: IconComponent;
  export const IconArrowUpRight: IconComponent;
  export const IconArrowUpLeft: IconComponent;
  export const IconArrowDownRight: IconComponent;
  export const IconArrowDownLeft: IconComponent;
  export const IconArrowsExpand: IconComponent;
  export const IconArrowsCollapse: IconComponent;
  export const IconArrowsMove: IconComponent;
  export const IconArrowsRotate: IconComponent;
  export const IconArrowsSwap: IconComponent;
  export const IconArrowsVertical: IconComponent;
  export const IconArrowsHorizontal: IconComponent;
  export const IconArrowsDiagonal: IconComponent;
  export const IconArrowsMaximize: IconComponent;
  export const IconArrowsMinimize: IconComponent;
  export const IconGridDots: IconComponent;
  export const IconGripVertical: IconComponent;
  export const IconGripHorizontal: IconComponent;
  export const IconDrag: IconComponent;
  export const IconMove: IconComponent;
  export const IconResize: IconComponent;
  export const IconPinned: IconComponent;
  export const IconPin: IconComponent;
  export const IconUnpin: IconComponent;
  export const IconAnchor: IconComponent;
  export const IconPaperclip: IconComponent;
  export const IconAttachment: IconComponent;
  export const IconNote: IconComponent;
  export const IconNotes: IconComponent;
  export const IconNotebook: IconComponent;
  export const IconJournal: IconComponent;
  export const IconDiary: IconComponent;
  export const IconBook: IconComponent;
  export const IconBooks: IconComponent;
  export const IconLibrary: IconComponent;
  export const IconArchive: IconComponent;
  export const IconBox: IconComponent;
  export const IconPackage: IconComponent;
  export const IconGift: IconComponent;
  export const IconPresent: IconComponent;
  export const IconSurprise: IconComponent;
  export const IconBalloon: IconComponent;
  export const IconConfetti: IconComponent;
  export const IconParty: IconComponent;
  export const IconCelebration: IconComponent;
  export const IconCake: IconComponent;
  export const IconCandle: IconComponent;
  export const IconFlower: IconComponent;
  export const IconPlant: IconComponent;
  export const IconTree: IconComponent;
  export const IconLeaf: IconComponent;
  export const IconSeedling: IconComponent;
  export const IconGrass: IconComponent;
  export const IconMountain: IconComponent;
  export const IconHill: IconComponent;
  export const IconValley: IconComponent;
  export const IconRiver: IconComponent;
  export const IconLake: IconComponent;
  export const IconOcean: IconComponent;
  export const IconSea: IconComponent;
  export const IconBeach: IconComponent;
  export const IconIsland: IconComponent;
  export const IconDesert: IconComponent;
  export const IconForest: IconComponent;
  export const IconJungle: IconComponent;
  export const IconSavanna: IconComponent;
  export const IconTundra: IconComponent;
  export const IconArctic: IconComponent;
  export const IconAntarctic: IconComponent;
  export const IconPolar: IconComponent;
  export const IconTropical: IconComponent;
  export const IconTemperate: IconComponent;
  export const IconArid: IconComponent;
  export const IconHumid: IconComponent;
  export const IconWet: IconComponent;
  export const IconDry: IconComponent;
  export const IconHot: IconComponent;
  export const IconCold: IconComponent;
  export const IconWarm: IconComponent;
  export const IconCool: IconComponent;
  // Add more as needed - this covers most common ones
}

declare module 'three-globe' {
  import { Object3D, Material } from 'three';
  
  class ThreeGlobe extends Object3D {
    constructor();
    globeImageUrl(url: string): this;
    bumpImageUrl(url: string): this;
    backgroundImageUrl(url: string): this;
    showAtmosphere(show: boolean): this;
    atmosphereColor(color: string): this;
    atmosphereAltitude(altitude: number): this;
    hexPolygonsData(data: unknown[]): this;
    hexPolygonResolution(resolution: number): this;
    hexPolygonMargin(margin: number): this;
    hexPolygonUseDots(useDots: boolean): this;
    hexPolygonColor(colorFn: (d: unknown) => string): this;
    hexPolygonLabel(labelFn: (d: unknown) => string): this;
    arcsData(data: unknown[]): this;
    arcStartLat(fn: (d: unknown) => number): this;
    arcStartLng(fn: (d: unknown) => number): this;
    arcEndLat(fn: (d: unknown) => number): this;
    arcEndLng(fn: (d: unknown) => number): this;
    arcColor(colorFn: (e: unknown) => string): this;
    arcAltitude(altitudeFn: (e: unknown) => number): this;
    arcStroke(strokeFn: () => number): this;
    arcDashLength(length: number): this;
    arcDashInitialGap(gapFn: (e: unknown) => number): this;
    arcDashGap(gap: number): this;
    arcDashAnimateTime(timeFn: () => number): this;
    pointsData(data: unknown[]): this;
    pointColor(colorOrFn: string | ((e: unknown) => string)): this;
    pointsMerge(merge: boolean): this;
    pointAltitude(altitude: number): this;
    pointRadius(radius: number): this;
    ringsData(data: unknown[]): this;
    ringColor(colorFn: (() => string) | string | ((t: number) => (e: unknown) => string)): this;
    ringMaxRadius(radiusOrFn: number | ((e: unknown) => number)): this;
    ringPropagationSpeed(speedOrFn: number | ((e: unknown) => number)): this;
    ringRepeatPeriod(periodOrFn: number | ((e: unknown) => number)): this;
    globeMaterial(): Material;
  }
  
  export default ThreeGlobe;
}
