"""
Canonical AU business lexicon for domain parsing and text analysis.
Used by: free_enrichment (domain keyword extraction), DM identification, message personalisation.
Directive: #328.3b
"""

# Business-type terms found in AU domain names.
# Used for semantic word-boundary detection when splitting compound domains.
BUSINESS_TERMS: frozenset[str] = frozenset(
    {
        # Dental
        "dental",
        "dentist",
        "dentists",
        "dentistry",
        "orthodontic",
        "orthodontics",
        # Medical/Health
        "medical",
        "health",
        "clinic",
        "clinics",
        "surgery",
        "hospital",
        "physiotherapy",
        "physio",
        "chiropractic",
        "chiro",
        "optometry",
        # Legal
        "legal",
        "law",
        "lawyer",
        "lawyers",
        "solicitor",
        "solicitors",
        "barrister",
        "barristers",
        "notary",
        # Trades
        "plumbing",
        "plumber",
        "plumbers",
        "electrical",
        "electrician",
        "building",
        "builder",
        "builders",
        "construction",
        "renovation",
        "renovations",
        "painting",
        "painter",
        "painters",
        # Professional services
        "accounting",
        "accountant",
        "accountants",
        "financial",
        "finance",
        "consulting",
        "consultant",
        "consultants",
        # Business structure words
        "group",
        "practice",
        "centre",
        "center",
        "house",
        "studio",
        "services",
        "solutions",
        "partners",
        "associates",
        "company",
        # Property
        "real",
        "estate",
        "property",
        "properties",
        "realty",
        # Other verticals
        "veterinary",
        "vet",
        "automotive",
        "auto",
        "fitness",
        "gym",
        "beauty",
        "salon",
        "spa",
        "restaurant",
        "cafe",
    }
)

# Common AU suburb/location names found in domain names.
# Top suburbs + directional + state capitals + major regional.
AU_SUBURBS: frozenset[str] = frozenset(
    {
        # State capitals
        "sydney",
        "melbourne",
        "brisbane",
        "perth",
        "adelaide",
        "hobart",
        "canberra",
        "darwin",
        # Major cities/regions
        "newcastle",
        "wollongong",
        "geelong",
        "goldcoast",
        "cairns",
        "townsville",
        "toowoomba",
        "ballarat",
        "bendigo",
        "launceston",
        "albury",
        "wodonga",
        "rockhampton",
        "mackay",
        "bunbury",
        "mandurah",
        "gladstone",
        "hervey",
        "mildura",
        "shepparton",
        # Sydney suburbs
        "parramatta",
        "bondi",
        "manly",
        "cronulla",
        "penrith",
        "blacktown",
        "liverpool",
        "bankstown",
        "hurstville",
        "burwood",
        "chatswood",
        "ryde",
        "epping",
        "hornsby",
        "pymble",
        "mosman",
        "kirribilli",
        "randwick",
        "maroubra",
        "coogee",
        "surry",
        "hills",
        "redfern",
        "glebe",
        "newtown",
        "camperdown",
        "balmain",
        "drummoyne",
        "strathfield",
        "ashfield",
        "marrickville",
        "canterbury",
        "kogarah",
        "sutherland",
        "miranda",
        "caringbah",
        "campbelltown",
        "camden",
        "wollondilly",
        "kellyville",
        "castle",
        # Melbourne suburbs
        "glenferrie",
        "hawthorn",
        "richmond",
        "collingwood",
        "fitzroy",
        "carlton",
        "brunswick",
        "northcote",
        "preston",
        "coburg",
        "essendon",
        "moonee",
        "footscray",
        "yarraville",
        "williamstown",
        "brighton",
        "sandringham",
        "cheltenham",
        "moorabbin",
        "dandenong",
        "frankston",
        "mornington",
        "cranbourne",
        "berwick",
        "pakenham",
        "melton",
        "werribee",
        "sunbury",
        "craigieburn",
        "heidelberg",
        "templestowe",
        "doncaster",
        "boxhill",
        "ringwood",
        "croydon",
        "lilydale",
        "ferntree",
        "glen",
        "waverley",
        "oakleigh",
        "caulfield",
        "malvern",
        "toorak",
        "prahran",
        "south",
        "yarra",
        "port",
        "albert",
        "kew",
        # Brisbane suburbs
        "southbank",
        "fortitude",
        "valley",
        "woolloongabba",
        "paddington",
        "toowong",
        "indooroopilly",
        "kenmore",
        "chapel",
        "springfield",
        "ipswich",
        "logan",
        "capalaba",
        "redlands",
        "wynnum",
        "sandgate",
        # Perth suburbs
        "fremantle",
        "joondalup",
        "rockingham",
        "armadale",
        "midland",
        "morley",
        "scarborough",
        "subiaco",
        "claremont",
        "nedlands",
        "cottesloe",
        "karrinyup",
        "stirling",
        "wanneroo",
        "ellenbrook",
        # Adelaide suburbs
        "norwood",
        "unley",
        "glenelg",
        "henley",
        "semaphore",
        "prospect",
        "walkerville",
        "burnside",
        # Directional terms (commonly in suburb names)
        "north",
        "east",
        "west",
        "upper",
        "lower",
        "mount",
        "point",
        "bay",
        "beach",
        "park",
        "vale",
        "lake",
        "creek",
        "hill",
        "heights",
        "grove",
    }
)

# Stopwords to drop from extracted keywords
DOMAIN_STOPWORDS: frozenset[str] = frozenset(
    {
        "the",
        "and",
        "of",
        "in",
        "at",
        "for",
        "by",
        "to",
        "a",
        "an",
        "com",
        "au",
        "www",
        "net",
        "org",
        "http",
        "https",
    }
)
