#!/usr/bin/env python3
"""cognee_session_start.py — write Cognee context snapshot to /tmp at agent session start.

KEI-107: 3-layer memory bring-up — session-start context injection.

Queries Cognee for the top-5 INSIGHTS relevant to the given callsign's recent
work context, then writes the results as readable markdown to
/tmp/cognee-context-<callsign>.md.

Agents read that file during session start (see .claude/modules/_session_start.md
step 7). Fail-open: if Cognee is unreachable or returns no results, the script
logs a warning and exits 0 — agent startup is never blocked.

Usage:
    python3 scripts/cognee_session_start.py --callsign elliot
    python3 scripts/cognee_session_start.py --callsign aiden --org-id keiracom_platform

Options:
    --callsign   Agent callsign (required). Scopes the Cognee node_set filter.
    --org-id     Cognee org scope (default: keiracom_platform).
    --app-id     Cognee app scope (default: agency_os).
    --top-k      Number of hits to fetch (default: 5).
    --query      Override the auto-generated wake query.
    --output     Override output path (default: /tmp/cognee-context-<callsign>.md).

Exit codes:
    0  always — script is fail-open by contract (agent start must never block).
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
import tempfile
from datetime import UTC, datetime
from pathlib import Path

# Make repo root importable when called from any cwd.
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

logging.basicConfig(
    level=logging.WARNING, format="%(levelname)s [cognee_session_start]: %(message)s"
)
logger = logging.getLogger("cognee_session_start")

DEFAULT_ORG = "keiracom_platform"
DEFAULT_APP = "agency_os"
DEFAULT_TOP_K = 5
MAX_HIT_CHARS = 600  # preview length per hit in the markdown output

_WAKE_QUERY_TEMPLATE = (
    "Recent decisions, open KEI issues, and current task context for callsign {callsign}. "
    "What should this agent resume on? What was decided or discovered in the last 24 hours?"
)


def _has_credentials() -> bool:
    """LiteLLM/Gemini key required for Cognee's embedding-backed search."""
    return bool(os.environ.get("GEMINI_API_KEY") or os.environ.get("LLM_API_KEY"))


def _load_env() -> None:
    """Inject discrete Cognee DB vars from DATABASE_URL_MIGRATIONS if needed.

    Mirrors the pattern in cognee_smoke.py — Cognee 1.0.9 pydantic-settings
    reads DB_HOST/PORT/etc not a full URL.
    """
    db_url = os.environ.get("DATABASE_URL_MIGRATIONS") or os.environ.get("DATABASE_URL")
    if not db_url:
        return
    from urllib.parse import urlparse

    p = urlparse(db_url)
    discrete = {
        "DB_HOST": p.hostname or "",
        "DB_PORT": str(p.port or ""),
        "DB_USERNAME": p.username or "",
        "DB_PASSWORD": p.password or "",
        "DB_NAME": p.path.lstrip("/") or "postgres",
        "VECTOR_DB_HOST": p.hostname or "",
        "VECTOR_DB_PORT": str(p.port or ""),
        "VECTOR_DB_USERNAME": p.username or "",
        "VECTOR_DB_PASSWORD": p.password or "",
        "VECTOR_DB_NAME": p.path.lstrip("/") or "postgres",
    }
    for k, v in discrete.items():
        os.environ.setdefault(k, v)


def _format_hits(hits: list, callsign: str, query: str, top_k: int) -> str:
    """Render hits as a markdown file for agent consumption."""
    ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# Cognee Session Context — {callsign}",
        "",
        f"Generated: {ts}  ",
        f"Query: `{query}`  ",
        f"Hits: {min(len(hits), top_k)} / {top_k} requested",
        "",
    ]
    if not hits:
        lines += ["_No Cognee results for this callsign. Fresh session with no prior context._", ""]
        return "\n".join(lines)

    lines.append("## Top Insights")
    lines.append("")
    for i, hit in enumerate(hits[:top_k], 1):
        text = str(hit).strip()
        preview = text[:MAX_HIT_CHARS]
        if len(text) > MAX_HIT_CHARS:
            preview += "…"
        lines += [f"### {i}.", "", preview, ""]

    lines += [
        "---",
        "_Context injected by scripts/cognee_session_start.py (KEI-107). "
        "Read-only — do not edit this file._",
        "",
    ]
    return "\n".join(lines)


def _search(query: str) -> list:
    """Query Cognee HTTP API. Bypasses SDK to avoid Ladybug DB lock conflict
    with running cognee.service. Fail-open: any error → returns [].
    """
    import json
    import urllib.error
    import urllib.parse
    import urllib.request

    base = os.environ.get("COGNEE_BASE_URL", "http://localhost:8000")
    user = os.environ.get("COGNEE_USER", "default_user@example.com")
    pw = os.environ.get("COGNEE_PASSWORD", "default_password")

    try:
        login_body = urllib.parse.urlencode({"username": user, "password": pw}).encode()
        req = urllib.request.Request(
            f"{base}/api/v1/auth/login",
            data=login_body,
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            token = json.loads(resp.read()).get("access_token")
        if not token:
            logger.warning("cognee: login returned no token")
            return []
        search_body = json.dumps({"search_type": "CHUNKS", "query": query, "top_k": 5}).encode()
        req = urllib.request.Request(
            f"{base}/api/v1/search",
            data=search_body,
            headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read()) or []
    except (urllib.error.URLError, json.JSONDecodeError) as exc:
        logger.warning("cognee HTTP query failed: %s", exc)
        return []


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--callsign", required=True, help="Agent callsign (e.g. elliot, aiden)")
    parser.add_argument("--org-id", default=DEFAULT_ORG)
    parser.add_argument("--app-id", default=DEFAULT_APP)
    parser.add_argument("--top-k", type=int, default=DEFAULT_TOP_K)
    parser.add_argument(
        "--query", default=None, help="Override wake query (auto-generated if omitted)"
    )
    parser.add_argument("--output", default=None, help="Override output path")
    args = parser.parse_args(argv)

    callsign = args.callsign.strip().lower()

    # LAW XVII callsign guard: if both --callsign and $CALLSIGN are set they must match.
    env_callsign = os.environ.get("CALLSIGN", "").strip().lower()
    if callsign and env_callsign and callsign != env_callsign:
        logger.warning(
            "--callsign %s disagrees with $CALLSIGN %s; using --callsign",
            callsign,
            env_callsign,
        )
    elif not callsign and not env_callsign:
        print(
            "ERROR [cognee_session_start]: --callsign is required and $CALLSIGN is not set.",
            file=sys.stderr,
        )
        sys.exit(2)
    elif not callsign:
        callsign = env_callsign

    tmp_dir = tempfile.gettempdir()
    output_path = (
        Path(args.output) if args.output else Path(tmp_dir) / f"cognee-context-{callsign}.md"
    )
    query = args.query or _WAKE_QUERY_TEMPLATE.format(callsign=callsign)

    # Always load discrete DB env vars from DATABASE_URL_MIGRATIONS.
    _load_env()

    # Fail-open gate: if no LLM key present, write a minimal stub and exit 0.
    if not _has_credentials():
        stub = (
            f"# Cognee Session Context — {callsign}\n\n"
            "_Skipped: GEMINI_API_KEY / LLM_API_KEY not set. "
            "Cognee search requires an LLM key._\n"
        )
        try:
            output_path.write_text(stub)
            print(f"[cognee_session_start] no LLM key — wrote stub to {output_path}", flush=True)
        except OSError as exc:
            logger.warning("could not write stub: %s", exc)
        return

    print(
        f"[cognee_session_start] callsign={callsign} org={args.org_id} app={args.app_id} top_k={args.top_k}",
        flush=True,
    )
    print(f"[cognee_session_start] query: {query}", flush=True)

    try:
        hits = _search(query)
    except Exception as exc:  # noqa: BLE001 — fail-open
        logger.warning("_search raised: %s", exc)
        hits = []

    print(f"[cognee_session_start] got {len(hits)} hit(s)", flush=True)

    content = _format_hits(hits, callsign, query, args.top_k)

    try:
        output_path.write_text(content, encoding="utf-8")
        print(f"[cognee_session_start] written → {output_path}", flush=True)
    except OSError as exc:
        logger.warning("could not write output file %s: %s", output_path, exc)
        # Still exit 0 — session must not block.


if __name__ == "__main__":
    main()
    sys.exit(0)
