"""governance_rules_atomizer — Phase Alpha governance-rules atomization (Agency_OS-blka sibling).

Extends Orion's atomization pipeline (PRs #1185/#1189/#1191) to process
governance rules from CLAUDE.md + session modules + LAW definitions into
Hindsight as governance-doc atoms. Goal per Dave directive 2026-05-27:
agents at spawn time retrieve ONLY relevant governance rules instead of
loading all of CLAUDE.md every spawn.

CONCUR-GATE check: SATISFIES — GOVERNANCE_ENFORCEMENT criterion
("domain-tool mappings versioned + ... + tenant isolation atom-store").

Sources (per dispatch):
  (a) ~/.claude/CLAUDE.md global rules
  (b) {repo}/CLAUDE.md project rules
  (c) {repo}/.claude/modules/*.md session modules
  (d) {repo}/docs/governance/CONSOLIDATED_RULES.md ratified rules
  (e) LAW I-A through LAW XVII definitions (live in CLAUDE.md +
      governance/*.md per repo convention; covered by (a)+(b)+(d))

Pipeline reuses Orion's `Atomizer` class with `source_kind="governance_doc"`
(already in VALID_SOURCE_KINDS per schema.py). No schema changes needed.
Each governance file produces N atoms via the LLM call; atoms carry the
canonical 7-field shape (trigger_condition + content + anti_pattern +
example + provenance + composition_tags + supersession_edges).

Cross-PR coordination with Orion's Decisions Atomization: NONE — this
pipeline reuses Orion's `Atomizer` + `AtomStore` + `Verifier` directly.
No dependency; no overlap.

CLI:
  python3 -m keiracom_system.atomization.governance_rules_atomizer \\
      --repo-root /home/elliotbot/clawd/Agency_OS \\
      --execute  # default is dry-run

bd: Agency_OS-blka (Phase Alpha — Governance Rules Atomization)
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from src.keiracom_system.atomization.atomizer import Atomizer, is_atomizer_enabled

log = logging.getLogger(__name__)

# Per dispatch: sources (a) through (d). LAW definitions covered implicitly
# via (a)+(b)+(d) since LAW I-A..XVII live in CLAUDE.md + governance/*.md.
DEFAULT_GLOBAL_CLAUDE_MD = Path.home() / ".claude" / "CLAUDE.md"
DEFAULT_STATE_FILE = Path("runtime/governance_rules_atomization_state.jsonl")
GOVERNANCE_SOURCE_KIND = "governance_doc"

# Per-file byte cap. Governance docs are typically <50KB; cap at 200KB to
# protect the LLM from accidentally pulling in a massive autogenerated file.
MAX_GOVERNANCE_BYTES = 200_000


class GovernanceRulesAtomizerError(RuntimeError):
    """Raised on invalid source or missing repo root."""


def iter_governance_sources(repo_root: Path, *, include_global: bool = True) -> Iterable[Path]:
    """Yield governance source paths in deterministic order.

    Order: global CLAUDE.md → project CLAUDE.md → modules/*.md (sorted) →
    governance/*.md (sorted). Determinism matters for state-file resume
    semantics + reproducible audit trails.
    """
    if include_global and DEFAULT_GLOBAL_CLAUDE_MD.exists():
        yield DEFAULT_GLOBAL_CLAUDE_MD

    project_claude = repo_root / "CLAUDE.md"
    if project_claude.exists():
        yield project_claude

    modules_dir = repo_root / ".claude" / "modules"
    if modules_dir.is_dir():
        yield from sorted(modules_dir.glob("*.md"))

    governance_dir = repo_root / "docs" / "governance"
    if governance_dir.is_dir():
        yield from sorted(governance_dir.glob("*.md"))


def load_state(path: Path) -> set[str]:
    """Read JSONL state file; return set of already-atomized source_refs.

    Same shape as skills_atomizer.load_state — only `ok=True` rows count
    as seen so failed attempts retry on re-run.
    """
    if not path.exists():
        return set()
    seen: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
            if row.get("ok") and row.get("source_ref"):
                seen.add(row["source_ref"])
        except json.JSONDecodeError:
            continue
    return seen


def append_state(path: Path, row: dict[str, Any]) -> None:
    """Append one JSONL row to the state file (idempotent).

    parents=True so first-run autocreates runtime/ dir.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(row) + "\n")


def atomize_governance_file(
    *,
    atomizer: Atomizer,
    governance_path: Path,
    repo_root: Path,
) -> tuple[bool, str]:
    """Atomize one governance file via Orion's Atomizer.

    Returns (ok, info). Byte-cap enforced before LLM call to avoid pulling
    in oversized files (defensive — would burn tokens with no atom output).
    """
    content = governance_path.read_text(encoding="utf-8")
    if len(content.encode("utf-8")) > MAX_GOVERNANCE_BYTES:
        return (
            False,
            f"governance file {governance_path} exceeds MAX_GOVERNANCE_BYTES={MAX_GOVERNANCE_BYTES}",
        )

    # source_ref shape matches skills_atomizer convention: stable across
    # absolute-path drift. Global CLAUDE.md uses `~/.claude/CLAUDE.md`
    # convention; in-repo files use `<repo>/<relpath>` shape.
    source_ref = _build_source_ref(governance_path, repo_root)

    try:
        job = atomizer.atomize(
            source_ref=source_ref,
            source_kind=GOVERNANCE_SOURCE_KIND,
            source_text=content,
        )
        return True, f"job_id={job.job_id} atoms={job.atoms_produced}"
    except Exception as exc:  # noqa: BLE001
        log.warning("governance atomize failed for %s: %s", governance_path, exc)
        return False, f"error: {exc}"


def _build_source_ref(governance_path: Path, repo_root: Path) -> str:
    """Build a stable source_ref string for a governance file path."""
    try:
        return f"governance/{governance_path.relative_to(repo_root)}"
    except ValueError:
        # Outside repo (e.g. global ~/.claude/CLAUDE.md). Use a stable label.
        if governance_path == DEFAULT_GLOBAL_CLAUDE_MD:
            return "governance/~/.claude/CLAUDE.md"
        return f"governance/{governance_path}"


def run(
    *,
    atomizer: Atomizer,
    repo_root: Path,
    state_path: Path,
    execute: bool,
    include_global: bool = True,
) -> int:
    """Walk governance sources + atomize each. Returns rc=0 clean / 1 on any fail."""
    if not repo_root.is_dir():
        log.error("repo_root %s missing", repo_root)
        return 2

    seen = load_state(state_path)
    log.info("state-file already-atomized: %d", len(seen))

    n_total = n_ok = n_fail = n_skip = 0
    for gov_path in iter_governance_sources(repo_root, include_global=include_global):
        n_total += 1
        source_ref = _build_source_ref(gov_path, repo_root)

        if source_ref in seen:
            n_skip += 1
            log.debug("skip already-atomized: %s", source_ref)
            continue

        if not execute:
            log.info("dry-run: would atomize %s", source_ref)
            continue

        ok, info = atomize_governance_file(
            atomizer=atomizer,
            governance_path=gov_path,
            repo_root=repo_root,
        )
        row: dict[str, Any] = {"source_ref": source_ref, "ok": ok, "info": info}
        append_state(state_path, row)
        if ok:
            n_ok += 1
        else:
            n_fail += 1
            log.warning("atomize %s FAILED: %s", source_ref, info)

    log.info(
        "summary: total=%d ok=%d fail=%d skip=%d (execute=%s)",
        n_total,
        n_ok,
        n_fail,
        n_skip,
        execute,
    )
    return 0 if n_fail == 0 else 1


def _check_feature_flag_or_warn() -> None:
    """Warn (don't fail) if KEIRACOM_ATOMIZER_ENABLED is off.

    Mirrors skills_atomizer._check_feature_flag_or_warn — operator running
    this without the production flag should see the discrepancy loudly.
    """
    if not is_atomizer_enabled():
        log.warning(
            "KEIRACOM_ATOMIZER_ENABLED is OFF — this run will execute even "
            "though the production feature flag would block atomization. "
            "Confirm intent before --execute."
        )


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        required=True,
        help="repo root containing CLAUDE.md + .claude/modules/ + docs/governance/",
    )
    parser.add_argument("--state-file", type=Path, default=DEFAULT_STATE_FILE)
    parser.add_argument(
        "--no-global",
        action="store_true",
        help="skip the ~/.claude/CLAUDE.md global source (default: include)",
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="actually run atomization (default: dry-run — list files only)",
    )
    parser.add_argument("--log-level", default="INFO")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """CLI entry. Caller wires up Atomizer + AtomStore via factory."""
    args = _parse_args(argv)
    logging.basicConfig(
        level=args.log_level,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    _check_feature_flag_or_warn()

    # Production deployment plugs in real Atomizer via a factory script.
    # Standalone CLI invocation only works in dry-run mode (no LLM/DB).
    if args.execute:
        log.error(
            "Standalone CLI cannot --execute without a wired Atomizer + AtomStore. "
            "Invoke via a production factory script that constructs the dependencies."
        )
        return 2

    log.info("dry-run: enumerating governance sources under %s", args.repo_root)
    for source_path in iter_governance_sources(args.repo_root, include_global=not args.no_global):
        print(_build_source_ref(source_path, args.repo_root))
    return 0


if __name__ == "__main__":
    sys.exit(main())
