/**
 * FILE: frontend/lib/demo-data.ts
 * PURPOSE: Comprehensive mock data for public demo mode
 * CEO Directive #028 — Public Demo Dashboard
 * 
 * Contains:
 * - 50 Leads across ALS tiers (6 Hot, 12 Warm, 20 Cool, 12 Cold)
 * - 3 Campaigns (active, draft, completed)
 * - 8-10 Inbox reply threads
 * - 30 days of report metrics
 * - Settings for "Horizon Digital" agency
 * - 2-3 leads with full enrichment timelines
 */

// ============================================
// TYPES
// ============================================

export type LeadTier = 'hot' | 'warm' | 'cool' | 'cold';
export type WhyHotReason = 'ceo' | 'founder' | 'active' | 'new-role' | 'hiring' | 'buyer' | 'executive' | 'decision-maker' | 'linkedin-active' | 'engaged';
export type Channel = 'email' | 'linkedin' | 'sms' | 'voice' | 'mail';
export type LeadStatus = 'sourced' | 'enriching' | 'enriched' | 'outreach' | 'replied' | 'meeting-booked' | 'active';
export type CampaignStatus = 'active' | 'draft' | 'completed' | 'paused';
export type IntentType = 'meeting' | 'interested' | 'question' | 'objection' | 'later';
export type SentimentType = 'positive' | 'negative' | 'neutral';

export interface DemoLead {
  id: string;
  name: string;
  title: string;
  company: string;
  email: string;
  phone?: string;
  location: string;
  abn: string;
  alsScore: number;
  tier: LeadTier;
  status: LeadStatus;
  whyHot: WhyHotReason[];
  channels: { type: Channel; active: boolean }[];
  lastActivity: string;
  industry: string;
  companySize: string;
  revenue: string;
  website?: string;
}

export interface DemoLeadDetail extends DemoLead {
  radarScores: {
    dataQuality: number;
    authority: number;
    companyFit: number;
    timing: number;
    risk: number;
  };
  timeline: Array<{
    id: string;
    type: string;
    title: string;
    detail?: string;
    time: string;
    date: string;
    badge?: string;
  }>;
  siegeWaterfall: Array<{
    tier: number;
    name: string;
    status: 'complete' | 'in-progress' | 'pending';
    source?: string;
    timestamp?: string;
  }>;
  notes: Array<{ id: string; text: string; author: string; date: string }>;
}

export interface DemoCampaign {
  id: string;
  name: string;
  status: CampaignStatus;
  isAI: boolean;
  channels: Channel[];
  dateRange: string;
  leadsEnrolled: number;
  metrics: {
    meetings: number;
    replyRate: string;
    openRate: string;
    showRate: string;
    avgALS: number;
  };
  sequence: Array<{
    step: number;
    channel: Channel;
    day: number;
    title: string;
    sent: number;
    opened?: number;
    replied?: number;
    status: 'completed' | 'active' | 'pending';
  }>;
}

export interface DemoInboxMessage {
  id: string;
  name: string;
  initials: string;
  company: string;
  title: string;
  email: string;
  phone?: string;
  score: number;
  tier: 'hot' | 'warm' | 'cool';
  channel: Channel;
  intent: IntentType;
  sentiment: SentimentType;
  preview: string;
  unread: boolean;
  timestamp: string;
  campaignName: string;
}

export interface DemoAgencyProfile {
  name: string;
  email: string;
  phone: string;
  company: string;
  timezone: string;
  initials: string;
  plan: string;
  website: string;
  abn: string;
}

// ============================================
// DEMO AGENCY PROFILE - Horizon Digital
// ============================================

export const demoAgencyProfile: DemoAgencyProfile = {
  name: 'Demo User',
  email: 'demo@horizondigital.com.au',
  phone: '+61 3 9123 4567',
  company: 'Horizon Digital',
  timezone: 'Australia/Melbourne (AEST)',
  initials: 'DU',
  plan: 'Ignition',
  website: 'horizondigital.com.au',
  abn: '51 824 753 556',
};

// ============================================
// 50 DEMO LEADS - Australian Businesses
// ============================================

export const demoLeads: DemoLead[] = [
  // === HOT LEADS (6) - Score ≥85 ===
  {
    id: 'lead-001',
    name: 'Sarah Chen',
    title: 'CEO',
    company: 'Bloom Digital Melbourne',
    email: 'sarah@bloomdigital.com.au',
    phone: '+61 412 345 678',
    location: 'Melbourne, VIC',
    abn: '12 345 678 901',
    alsScore: 94,
    tier: 'hot',
    status: 'replied',
    whyHot: ['ceo', 'active', 'buyer'],
    channels: [{ type: 'email', active: true }, { type: 'linkedin', active: true }, { type: 'voice', active: true }],
    lastActivity: '2 min ago',
    industry: 'Digital Marketing',
    companySize: '15-25',
    revenue: '$2-5M',
    website: 'bloomdigital.com.au',
  },
  {
    id: 'lead-002',
    name: 'Marcus Webb',
    title: 'Founder',
    company: 'GrowthLabs Sydney',
    email: 'marcus@growthlabs.com.au',
    phone: '+61 421 987 654',
    location: 'Sydney, NSW',
    abn: '23 456 789 012',
    alsScore: 91,
    tier: 'hot',
    status: 'meeting-booked',
    whyHot: ['founder', 'hiring', 'linkedin-active'],
    channels: [{ type: 'email', active: true }, { type: 'linkedin', active: true }, { type: 'sms', active: true }],
    lastActivity: '15 min ago',
    industry: 'SaaS / Growth Marketing',
    companySize: '25-50',
    revenue: '$5-10M',
    website: 'growthlabs.com.au',
  },
  {
    id: 'lead-003',
    name: 'David Park',
    title: 'Managing Director',
    company: 'Momentum Media',
    email: 'david@momentummedia.com.au',
    phone: '+61 433 111 222',
    location: 'Brisbane, QLD',
    abn: '34 567 890 123',
    alsScore: 89,
    tier: 'hot',
    status: 'replied',
    whyHot: ['executive', 'buyer', 'engaged'],
    channels: [{ type: 'email', active: true }, { type: 'linkedin', active: true }],
    lastActivity: '1 hour ago',
    industry: 'Media & Advertising',
    companySize: '50-100',
    revenue: '$10-25M',
    website: 'momentummedia.com.au',
  },
  {
    id: 'lead-004',
    name: 'Jennifer Wu',
    title: 'Owner',
    company: 'Smile Dental Fitzroy',
    email: 'jennifer@smiledentalfitzroy.com.au',
    phone: '+61 400 333 444',
    location: 'Fitzroy, VIC',
    abn: '45 678 901 234',
    alsScore: 88,
    tier: 'hot',
    status: 'outreach',
    whyHot: ['decision-maker', 'active'],
    channels: [{ type: 'email', active: true }, { type: 'sms', active: true }, { type: 'voice', active: true }],
    lastActivity: '2 hours ago',
    industry: 'Healthcare / Dental',
    companySize: '5-15',
    revenue: '$1-2M',
    website: 'smiledentalfitzroy.com.au',
  },
  {
    id: 'lead-005',
    name: 'Michael Nguyen',
    title: 'Principal',
    company: 'Melbourne Dental Care',
    email: 'michael@melbournedental.com.au',
    phone: '+61 411 555 666',
    location: 'Melbourne CBD, VIC',
    abn: '56 789 012 345',
    alsScore: 87,
    tier: 'hot',
    status: 'enriched',
    whyHot: ['decision-maker', 'new-role'],
    channels: [{ type: 'email', active: true }, { type: 'linkedin', active: true }],
    lastActivity: '3 hours ago',
    industry: 'Healthcare / Dental',
    companySize: '10-20',
    revenue: '$2-5M',
    website: 'melbournedental.com.au',
  },
  {
    id: 'lead-006',
    name: 'Lisa Wong',
    title: 'Founder & CEO',
    company: 'Pixel Perfect Agency',
    email: 'lisa@pixelperfect.com.au',
    phone: '+61 422 777 888',
    location: 'South Yarra, VIC',
    abn: '67 890 123 456',
    alsScore: 85,
    tier: 'hot',
    status: 'active',
    whyHot: ['founder', 'buyer', 'linkedin-active'],
    channels: [{ type: 'email', active: true }, { type: 'linkedin', active: true }, { type: 'voice', active: false }],
    lastActivity: '4 hours ago',
    industry: 'Creative Agency',
    companySize: '20-35',
    revenue: '$3-7M',
    website: 'pixelperfect.com.au',
  },

  // === WARM LEADS (12) - Score 60-84 ===
  {
    id: 'lead-007',
    name: 'James Cooper',
    title: 'Owner',
    company: 'Cooper Electrical Services',
    email: 'james@cooperelectrical.com.au',
    phone: '+61 433 222 333',
    location: 'Preston, VIC',
    abn: '78 901 234 567',
    alsScore: 82,
    tier: 'warm',
    status: 'enriched',
    whyHot: ['decision-maker', 'engaged'],
    channels: [{ type: 'email', active: true }, { type: 'sms', active: true }],
    lastActivity: '1 day ago',
    industry: 'Trades / Electrical',
    companySize: '10-20',
    revenue: '$1-3M',
    website: 'cooperelectrical.com.au',
  },
  {
    id: 'lead-008',
    name: 'Emma Wilson',
    title: 'Head of Marketing',
    company: 'Coastal Digital',
    email: 'emma@coastaldigital.com.au',
    location: 'Bondi, NSW',
    abn: '89 012 345 678',
    alsScore: 78,
    tier: 'warm',
    status: 'outreach',
    whyHot: ['executive', 'active'],
    channels: [{ type: 'email', active: true }, { type: 'linkedin', active: true }],
    lastActivity: '2 days ago',
    industry: 'Digital Marketing',
    companySize: '15-30',
    revenue: '$2-5M',
  },
  {
    id: 'lead-009',
    name: 'Tom Brown',
    title: 'Director',
    company: 'Scale Trades Australia',
    email: 'tom@scaletrades.com.au',
    phone: '+61 444 555 666',
    location: 'Parramatta, NSW',
    abn: '90 123 456 789',
    alsScore: 76,
    tier: 'warm',
    status: 'enriching',
    whyHot: ['executive'],
    channels: [{ type: 'email', active: true }],
    lastActivity: '3 days ago',
    industry: 'Trades / General',
    companySize: '20-40',
    revenue: '$3-6M',
  },
  {
    id: 'lead-010',
    name: 'Rachel Nguyen',
    title: 'Practice Manager',
    company: 'Growth Dental Kew',
    email: 'rachel@growthdentalkew.com.au',
    location: 'Kew, VIC',
    abn: '01 234 567 890',
    alsScore: 74,
    tier: 'warm',
    status: 'enriched',
    whyHot: ['decision-maker'],
    channels: [{ type: 'email', active: true }, { type: 'linkedin', active: true }],
    lastActivity: '2 days ago',
    industry: 'Healthcare / Dental',
    companySize: '5-10',
    revenue: '$1-2M',
  },
  {
    id: 'lead-011',
    name: 'Chris Anderson',
    title: 'Managing Partner',
    company: 'Anderson Accounting',
    email: 'chris@andersonaccounting.com.au',
    phone: '+61 455 666 777',
    location: 'Brisbane CBD, QLD',
    abn: '12 345 678 902',
    alsScore: 72,
    tier: 'warm',
    status: 'outreach',
    whyHot: ['executive', 'buyer'],
    channels: [{ type: 'email', active: true }, { type: 'linkedin', active: true }],
    lastActivity: '4 days ago',
    industry: 'Professional Services / Accounting',
    companySize: '10-25',
    revenue: '$2-4M',
  },
  {
    id: 'lead-012',
    name: 'Anna Smith',
    title: 'Marketing Director',
    company: 'Digital First Agency',
    email: 'anna@digitalfirst.com.au',
    location: 'St Kilda, VIC',
    abn: '23 456 789 013',
    alsScore: 70,
    tier: 'warm',
    status: 'enriched',
    whyHot: ['executive', 'linkedin-active'],
    channels: [{ type: 'email', active: true }, { type: 'linkedin', active: true }],
    lastActivity: '5 days ago',
    industry: 'Digital Marketing',
    companySize: '15-25',
    revenue: '$2-4M',
  },
  {
    id: 'lead-013',
    name: 'Steve Martinez',
    title: 'Owner',
    company: 'TradeFlow Plumbing',
    email: 'steve@tradeflowplumbing.com.au',
    phone: '+61 466 777 888',
    location: 'Frankston, VIC',
    abn: '34 567 890 124',
    alsScore: 68,
    tier: 'warm',
    status: 'sourced',
    whyHot: ['decision-maker'],
    channels: [{ type: 'email', active: true }, { type: 'sms', active: true }],
    lastActivity: '1 week ago',
    industry: 'Trades / Plumbing',
    companySize: '5-15',
    revenue: '$800K-1.5M',
  },
  {
    id: 'lead-014',
    name: 'Kate Thompson',
    title: 'CEO',
    company: 'Bright Smile Clinic',
    email: 'kate@brightsmileclinic.com.au',
    location: 'Toorak, VIC',
    abn: '45 678 901 235',
    alsScore: 66,
    tier: 'warm',
    status: 'enriching',
    whyHot: ['ceo'],
    channels: [{ type: 'email', active: true }],
    lastActivity: '1 week ago',
    industry: 'Healthcare / Dental',
    companySize: '8-15',
    revenue: '$1.5-3M',
  },
  {
    id: 'lead-015',
    name: 'Ryan Kelly',
    title: 'Operations Manager',
    company: 'Kelly Construction',
    email: 'ryan@kellyconstruction.com.au',
    phone: '+61 477 888 999',
    location: 'Gold Coast, QLD',
    abn: '56 789 012 346',
    alsScore: 64,
    tier: 'warm',
    status: 'outreach',
    whyHot: ['executive'],
    channels: [{ type: 'email', active: true }, { type: 'voice', active: true }],
    lastActivity: '6 days ago',
    industry: 'Construction',
    companySize: '25-50',
    revenue: '$5-10M',
  },
  {
    id: 'lead-016',
    name: 'Michelle Lee',
    title: 'Principal Dentist',
    company: 'Family Dental Brunswick',
    email: 'michelle@familydental.com.au',
    location: 'Brunswick, VIC',
    abn: '67 890 123 457',
    alsScore: 62,
    tier: 'warm',
    status: 'enriched',
    whyHot: ['decision-maker'],
    channels: [{ type: 'email', active: true }, { type: 'sms', active: true }],
    lastActivity: '1 week ago',
    industry: 'Healthcare / Dental',
    companySize: '5-12',
    revenue: '$1-2M',
  },
  {
    id: 'lead-017',
    name: 'Peter Chang',
    title: 'Founder',
    company: 'Digital Edge Agency',
    email: 'peter@digitaledge.com.au',
    location: 'Surry Hills, NSW',
    abn: '78 901 234 568',
    alsScore: 61,
    tier: 'warm',
    status: 'sourced',
    whyHot: ['founder'],
    channels: [{ type: 'email', active: true }, { type: 'linkedin', active: true }],
    lastActivity: '1 week ago',
    industry: 'Digital Marketing',
    companySize: '10-20',
    revenue: '$1.5-3M',
  },
  {
    id: 'lead-018',
    name: 'Sandra Hughes',
    title: 'Business Owner',
    company: 'Hughes Café Group',
    email: 'sandra@hughescafe.com.au',
    phone: '+61 488 999 000',
    location: 'Collingwood, VIC',
    abn: '89 012 345 679',
    alsScore: 60,
    tier: 'warm',
    status: 'enriching',
    whyHot: ['decision-maker'],
    channels: [{ type: 'email', active: true }, { type: 'sms', active: true }],
    lastActivity: '8 days ago',
    industry: 'Hospitality / Café',
    companySize: '20-40',
    revenue: '$2-4M',
  },

  // === COOL LEADS (20) - Score 35-59 ===
  {
    id: 'lead-019',
    name: 'Daniel Lee',
    title: 'Marketing Manager',
    company: 'Spark Creative',
    email: 'daniel@sparkcreative.com.au',
    location: 'Richmond, VIC',
    abn: '90 123 456 780',
    alsScore: 58,
    tier: 'cool',
    status: 'enriched',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '2 weeks ago',
    industry: 'Creative Agency',
    companySize: '8-15',
    revenue: '$800K-1.5M',
  },
  {
    id: 'lead-020',
    name: 'Sophie Martinez',
    title: 'Account Manager',
    company: 'Metro Media Solutions',
    email: 'sophie@metromedia.com.au',
    location: 'North Sydney, NSW',
    abn: '01 234 567 891',
    alsScore: 56,
    tier: 'cool',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '2 weeks ago',
    industry: 'Media & Advertising',
    companySize: '15-30',
    revenue: '$2-4M',
  },
  {
    id: 'lead-021',
    name: 'Andrew White',
    title: 'Office Manager',
    company: 'Clearview Optometry',
    email: 'andrew@clearviewoptom.com.au',
    location: 'Hawthorn, VIC',
    abn: '12 345 678 903',
    alsScore: 54,
    tier: 'cool',
    status: 'enriching',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '10 days ago',
    industry: 'Healthcare / Optometry',
    companySize: '5-10',
    revenue: '$500K-1M',
  },
  {
    id: 'lead-022',
    name: 'Lauren Taylor',
    title: 'HR Manager',
    company: 'Taylor Engineering',
    email: 'lauren@tayloreng.com.au',
    location: 'Docklands, VIC',
    abn: '23 456 789 014',
    alsScore: 52,
    tier: 'cool',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: true }, { type: 'linkedin', active: false }],
    lastActivity: '2 weeks ago',
    industry: 'Engineering',
    companySize: '30-50',
    revenue: '$5-10M',
  },
  {
    id: 'lead-023',
    name: 'Ben Harris',
    title: 'Sales Manager',
    company: 'AutoParts Direct',
    email: 'ben@autopartsdirect.com.au',
    location: 'Dandenong, VIC',
    abn: '34 567 890 125',
    alsScore: 50,
    tier: 'cool',
    status: 'enriched',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '3 weeks ago',
    industry: 'Automotive / Parts',
    companySize: '10-25',
    revenue: '$2-5M',
  },
  {
    id: 'lead-024',
    name: 'Jessica Brown',
    title: 'Practice Coordinator',
    company: 'Sunshine Physiotherapy',
    email: 'jessica@sunshinephysio.com.au',
    location: 'Sunshine, VIC',
    abn: '45 678 901 236',
    alsScore: 49,
    tier: 'cool',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '2 weeks ago',
    industry: 'Healthcare / Physiotherapy',
    companySize: '5-12',
    revenue: '$500K-1M',
  },
  {
    id: 'lead-025',
    name: 'Mark Wilson',
    title: 'Branch Manager',
    company: 'Regional Finance Co',
    email: 'mark@regionalfinance.com.au',
    location: 'Geelong, VIC',
    abn: '56 789 012 347',
    alsScore: 48,
    tier: 'cool',
    status: 'enriching',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '3 weeks ago',
    industry: 'Financial Services',
    companySize: '10-20',
    revenue: '$1-3M',
  },
  {
    id: 'lead-026',
    name: 'Nicole Adams',
    title: 'Studio Owner',
    company: 'FitLife Gym Prahran',
    email: 'nicole@fitlifegym.com.au',
    phone: '+61 499 111 222',
    location: 'Prahran, VIC',
    abn: '67 890 123 458',
    alsScore: 47,
    tier: 'cool',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: true }, { type: 'sms', active: false }],
    lastActivity: '2 weeks ago',
    industry: 'Fitness / Gym',
    companySize: '5-10',
    revenue: '$300K-700K',
  },
  {
    id: 'lead-027',
    name: 'Greg Morrison',
    title: 'Senior Accountant',
    company: 'Morrison & Partners',
    email: 'greg@morrisonpartners.com.au',
    location: 'Melbourne CBD, VIC',
    abn: '78 901 234 569',
    alsScore: 46,
    tier: 'cool',
    status: 'enriched',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '3 weeks ago',
    industry: 'Professional Services / Accounting',
    companySize: '8-15',
    revenue: '$1-2M',
  },
  {
    id: 'lead-028',
    name: 'Amy Chen',
    title: 'Operations Lead',
    company: 'Express Logistics',
    email: 'amy@expresslogistics.com.au',
    location: 'Tullamarine, VIC',
    abn: '89 012 345 670',
    alsScore: 45,
    tier: 'cool',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '4 weeks ago',
    industry: 'Logistics / Transport',
    companySize: '25-50',
    revenue: '$5-10M',
  },
  {
    id: 'lead-029',
    name: 'Tim Roberts',
    title: 'Café Owner',
    company: 'Bean Counter Coffee',
    email: 'tim@beancountercoffee.com.au',
    phone: '+61 400 222 333',
    location: 'Fitzroy, VIC',
    abn: '90 123 456 781',
    alsScore: 44,
    tier: 'cool',
    status: 'enriching',
    whyHot: [],
    channels: [{ type: 'email', active: true }, { type: 'sms', active: true }],
    lastActivity: '3 weeks ago',
    industry: 'Hospitality / Café',
    companySize: '5-10',
    revenue: '$400K-800K',
  },
  {
    id: 'lead-030',
    name: 'Diana Patel',
    title: 'Marketing Coordinator',
    company: 'Urban Living Properties',
    email: 'diana@urbanliving.com.au',
    location: 'South Melbourne, VIC',
    abn: '01 234 567 892',
    alsScore: 43,
    tier: 'cool',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '3 weeks ago',
    industry: 'Real Estate',
    companySize: '15-30',
    revenue: '$3-7M',
  },
  {
    id: 'lead-031',
    name: 'Paul Jackson',
    title: 'IT Manager',
    company: 'SecureTech Solutions',
    email: 'paul@securetech.com.au',
    location: 'Chatswood, NSW',
    abn: '12 345 678 904',
    alsScore: 42,
    tier: 'cool',
    status: 'enriched',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '4 weeks ago',
    industry: 'IT / Security',
    companySize: '10-25',
    revenue: '$1.5-3M',
  },
  {
    id: 'lead-032',
    name: 'Samantha Lee',
    title: 'Salon Owner',
    company: 'Style & Grace Hair',
    email: 'sam@styleandgrace.com.au',
    phone: '+61 411 333 444',
    location: 'Chapel Street, VIC',
    abn: '23 456 789 015',
    alsScore: 41,
    tier: 'cool',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '3 weeks ago',
    industry: 'Beauty / Hair Salon',
    companySize: '5-10',
    revenue: '$300K-600K',
  },
  {
    id: 'lead-033',
    name: 'Chris Davis',
    title: 'Restaurant Manager',
    company: 'The Italian Table',
    email: 'chris@italiantable.com.au',
    location: 'Lygon Street, VIC',
    abn: '34 567 890 126',
    alsScore: 40,
    tier: 'cool',
    status: 'enriching',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '4 weeks ago',
    industry: 'Hospitality / Restaurant',
    companySize: '15-25',
    revenue: '$1-2M',
  },
  {
    id: 'lead-034',
    name: 'Rebecca Moore',
    title: 'Office Administrator',
    company: 'Melbourne Legal Group',
    email: 'rebecca@melblegal.com.au',
    location: 'Collins Street, VIC',
    abn: '45 678 901 237',
    alsScore: 39,
    tier: 'cool',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '1 month ago',
    industry: 'Legal Services',
    companySize: '20-40',
    revenue: '$4-8M',
  },
  {
    id: 'lead-035',
    name: 'Kevin Tan',
    title: 'Store Manager',
    company: 'HomeStyle Furniture',
    email: 'kevin@homestylefurniture.com.au',
    location: 'Nunawading, VIC',
    abn: '56 789 012 348',
    alsScore: 38,
    tier: 'cool',
    status: 'enriched',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '1 month ago',
    industry: 'Retail / Furniture',
    companySize: '10-20',
    revenue: '$2-4M',
  },
  {
    id: 'lead-036',
    name: 'Natalie Ford',
    title: 'Practice Manager',
    company: 'Bayside Veterinary',
    email: 'natalie@baysidevet.com.au',
    location: 'Brighton, VIC',
    abn: '67 890 123 459',
    alsScore: 37,
    tier: 'cool',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '1 month ago',
    industry: 'Healthcare / Veterinary',
    companySize: '8-15',
    revenue: '$800K-1.5M',
  },
  {
    id: 'lead-037',
    name: 'Jake Williams',
    title: 'Workshop Manager',
    company: 'Williams Auto Service',
    email: 'jake@williamsauto.com.au',
    phone: '+61 422 444 555',
    location: 'Clayton, VIC',
    abn: '78 901 234 560',
    alsScore: 36,
    tier: 'cool',
    status: 'enriching',
    whyHot: [],
    channels: [{ type: 'email', active: true }, { type: 'sms', active: true }],
    lastActivity: '1 month ago',
    industry: 'Automotive / Service',
    companySize: '5-12',
    revenue: '$500K-1M',
  },
  {
    id: 'lead-038',
    name: 'Megan Scott',
    title: 'Events Coordinator',
    company: 'Premier Events Co',
    email: 'megan@premierevents.com.au',
    location: 'Southbank, VIC',
    abn: '89 012 345 671',
    alsScore: 35,
    tier: 'cool',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: true }],
    lastActivity: '1 month ago',
    industry: 'Events / Planning',
    companySize: '10-20',
    revenue: '$1-2M',
  },

  // === COLD LEADS (12) - Score 30-34 ===
  {
    id: 'lead-039',
    name: 'Gary Thompson',
    title: 'Junior Accountant',
    company: 'Numbers Plus',
    email: 'gary@numbersplus.com.au',
    location: 'Box Hill, VIC',
    abn: '90 123 456 782',
    alsScore: 34,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '2 months ago',
    industry: 'Professional Services / Accounting',
    companySize: '5-10',
    revenue: '$500K-800K',
  },
  {
    id: 'lead-040',
    name: 'Helen Baker',
    title: 'Receptionist',
    company: 'City Medical Centre',
    email: 'helen@citymedical.com.au',
    location: 'Melbourne CBD, VIC',
    abn: '01 234 567 893',
    alsScore: 33,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '2 months ago',
    industry: 'Healthcare / Medical',
    companySize: '15-25',
    revenue: '$2-4M',
  },
  {
    id: 'lead-041',
    name: 'Brian Mills',
    title: 'Sales Rep',
    company: 'Industrial Supplies Co',
    email: 'brian@industrialsupplies.com.au',
    location: 'Campbellfield, VIC',
    abn: '12 345 678 905',
    alsScore: 33,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '6 weeks ago',
    industry: 'Industrial / Supplies',
    companySize: '10-20',
    revenue: '$1.5-3M',
  },
  {
    id: 'lead-042',
    name: 'Caroline Young',
    title: 'Admin Assistant',
    company: 'Southern Plumbing',
    email: 'caroline@southernplumbing.com.au',
    location: 'Moorabbin, VIC',
    abn: '23 456 789 016',
    alsScore: 32,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '2 months ago',
    industry: 'Trades / Plumbing',
    companySize: '5-10',
    revenue: '$400K-800K',
  },
  {
    id: 'lead-043',
    name: 'Frank Chen',
    title: 'Warehouse Supervisor',
    company: 'QuickShip Logistics',
    email: 'frank@quickship.com.au',
    location: 'Laverton, VIC',
    abn: '34 567 890 127',
    alsScore: 32,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '2 months ago',
    industry: 'Logistics / Warehouse',
    companySize: '20-35',
    revenue: '$3-6M',
  },
  {
    id: 'lead-044',
    name: 'Linda Evans',
    title: 'Front Desk Manager',
    company: 'Parkview Hotel',
    email: 'linda@parkviewhotel.com.au',
    location: 'Carlton, VIC',
    abn: '45 678 901 238',
    alsScore: 31,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '3 months ago',
    industry: 'Hospitality / Hotel',
    companySize: '25-50',
    revenue: '$3-6M',
  },
  {
    id: 'lead-045',
    name: 'Alan King',
    title: 'Project Coordinator',
    company: 'BuildRight Construction',
    email: 'alan@buildright.com.au',
    location: 'Footscray, VIC',
    abn: '56 789 012 349',
    alsScore: 31,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '2 months ago',
    industry: 'Construction',
    companySize: '30-60',
    revenue: '$8-15M',
  },
  {
    id: 'lead-046',
    name: 'Vanessa Pham',
    title: 'Junior Designer',
    company: 'Creative Hub Studio',
    email: 'vanessa@creativehub.com.au',
    location: 'Brunswick East, VIC',
    abn: '67 890 123 450',
    alsScore: 31,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '6 weeks ago',
    industry: 'Creative / Design',
    companySize: '5-10',
    revenue: '$300K-600K',
  },
  {
    id: 'lead-047',
    name: 'Ross Mitchell',
    title: 'Driver Manager',
    company: 'Metro Courier Services',
    email: 'ross@metrocourier.com.au',
    location: 'Heidelberg, VIC',
    abn: '78 901 234 561',
    alsScore: 30,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '3 months ago',
    industry: 'Logistics / Courier',
    companySize: '15-30',
    revenue: '$1.5-3M',
  },
  {
    id: 'lead-048',
    name: 'Wendy Clark',
    title: 'Booking Agent',
    company: 'Travel Plus Australia',
    email: 'wendy@travelplus.com.au',
    location: 'Camberwell, VIC',
    abn: '89 012 345 672',
    alsScore: 30,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '3 months ago',
    industry: 'Travel / Tourism',
    companySize: '8-15',
    revenue: '$1-2M',
  },
  {
    id: 'lead-049',
    name: 'Simon Turner',
    title: 'Assistant Manager',
    company: 'Fresh Market Grocers',
    email: 'simon@freshmarket.com.au',
    location: 'Prahran Market, VIC',
    abn: '90 123 456 783',
    alsScore: 30,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '2 months ago',
    industry: 'Retail / Grocery',
    companySize: '10-20',
    revenue: '$800K-1.5M',
  },
  {
    id: 'lead-050',
    name: 'Olivia Reed',
    title: 'Retail Associate',
    company: 'Fashion Forward Boutique',
    email: 'olivia@fashionforward.com.au',
    location: 'Chapel Street, VIC',
    abn: '01 234 567 894',
    alsScore: 30,
    tier: 'cold',
    status: 'sourced',
    whyHot: [],
    channels: [{ type: 'email', active: false }],
    lastActivity: '3 months ago',
    industry: 'Retail / Fashion',
    companySize: '3-8',
    revenue: '$200K-400K',
  },
];

// Lead stats computed from demoLeads
export const demoLeadStats = {
  total: demoLeads.length,
  hot: demoLeads.filter(l => l.tier === 'hot').length,
  warm: demoLeads.filter(l => l.tier === 'warm').length,
  cool: demoLeads.filter(l => l.tier === 'cool').length,
  cold: demoLeads.filter(l => l.tier === 'cold').length,
  avgALS: Math.round(demoLeads.reduce((sum, l) => sum + l.alsScore, 0) / demoLeads.length),
};

// ============================================
// LEADS WITH FULL ENRICHMENT TIMELINES (3)
// ============================================

export const demoLeadDetails: Record<string, DemoLeadDetail> = {
  'lead-001': {
    ...demoLeads[0],
    radarScores: {
      dataQuality: 92,
      authority: 98,
      companyFit: 88,
      timing: 95,
      risk: 15,
    },
    timeline: [
      { id: 't1', type: 'reply', title: 'Replied to Email', detail: '"Yes, I\'d love to learn more. Can we schedule a call?"', time: '10:42 AM', date: 'Today', badge: 'Positive' },
      { id: 't2', type: 'email', title: 'Email opened (5th time)', detail: 'Subject: "Quick question about Bloom Digital"', time: '10:38 AM', date: 'Today', badge: 'opened' },
      { id: 't3', type: 'voice', title: 'Voice AI Call', detail: '3 min 24 sec call — AI detected buying interest', time: '4:30 PM', date: 'Yesterday', badge: 'Meeting Booked' },
      { id: 't4', type: 'linkedin', title: 'LinkedIn Connection Accepted', detail: 'Sarah accepted your connection request', time: '11:20 AM', date: 'Yesterday' },
      { id: 't5', type: 'email', title: 'Initial outreach sent', detail: 'Personalized email about scaling marketing operations', time: '9:00 AM', date: 'Feb 10, 2026' },
      { id: 't6', type: 'enrichment', title: 'Lead enriched via Siege Waterfall', detail: 'ABN → GMB → Hunter → LinkedIn', time: '11:00 AM', date: 'Feb 9, 2026' },
    ],
    siegeWaterfall: [
      { tier: 1, name: 'ABN Lookup', status: 'complete', source: 'ABR', timestamp: '3 days ago' },
      { tier: 2, name: 'GMB Enrichment', status: 'complete', source: 'Google', timestamp: '3 days ago' },
      { tier: 3, name: 'Email Discovery', status: 'complete', source: 'Hunter.io', timestamp: '3 days ago' },
      { tier: 4, name: 'LinkedIn Profile', status: 'complete', source: 'LinkedIn', timestamp: '2 days ago' },
      { tier: 5, name: 'Deep Intel', status: 'complete', source: 'DataForSEO', timestamp: '1 day ago' },
    ],
    notes: [
      { id: 'n1', text: 'Very responsive on LinkedIn. Mentioned budget approval in Q1.', author: 'Demo User', date: 'Today, 10:15 AM' },
      { id: 'n2', text: 'Initial research shows strong ICP match - digital agency looking to scale.', author: 'Demo User', date: 'Feb 9, 2026' },
    ],
  },
  'lead-002': {
    ...demoLeads[1],
    radarScores: {
      dataQuality: 88,
      authority: 95,
      companyFit: 90,
      timing: 85,
      risk: 20,
    },
    timeline: [
      { id: 't1', type: 'meeting', title: 'Meeting Booked', detail: 'Discovery call scheduled for Thursday 10am AEST', time: '2:15 PM', date: 'Today', badge: 'Booked' },
      { id: 't2', type: 'sms', title: 'SMS Confirmed', detail: '"Perfect, Thursday works!"', time: '2:12 PM', date: 'Today', badge: 'replied' },
      { id: 't3', type: 'voice', title: 'Voice AI Call', detail: '4 min 12 sec call — confirmed interest in growth services', time: '11:30 AM', date: 'Today' },
      { id: 't4', type: 'email', title: 'Email opened (3rd time)', detail: 'Subject: "GrowthLabs scaling story"', time: '9:45 AM', date: 'Today' },
      { id: 't5', type: 'linkedin', title: 'LinkedIn Message Sent', detail: 'Follow-up with case study link', time: '3:00 PM', date: 'Yesterday' },
      { id: 't6', type: 'enrichment', title: 'Lead enriched via Siege Waterfall', detail: 'Full profile complete', time: '10:00 AM', date: 'Feb 8, 2026' },
    ],
    siegeWaterfall: [
      { tier: 1, name: 'ABN Lookup', status: 'complete', source: 'ABR', timestamp: '5 days ago' },
      { tier: 2, name: 'GMB Enrichment', status: 'complete', source: 'Google', timestamp: '5 days ago' },
      { tier: 3, name: 'Email Discovery', status: 'complete', source: 'Hunter.io', timestamp: '4 days ago' },
      { tier: 4, name: 'LinkedIn Profile', status: 'complete', source: 'LinkedIn', timestamp: '4 days ago' },
      { tier: 5, name: 'Deep Intel', status: 'complete', source: 'DataForSEO', timestamp: '3 days ago' },
    ],
    notes: [
      { id: 'n1', text: 'Founder actively hiring - great timing for our services.', author: 'Demo User', date: 'Today, 2:30 PM' },
    ],
  },
  'lead-003': {
    ...demoLeads[2],
    radarScores: {
      dataQuality: 85,
      authority: 88,
      companyFit: 82,
      timing: 78,
      risk: 25,
    },
    timeline: [
      { id: 't1', type: 'reply', title: 'Replied to Email', detail: '"Interesting approach. Can you send more info on pricing?"', time: '11:15 AM', date: 'Today', badge: 'Interested' },
      { id: 't2', type: 'email', title: 'Email opened (2nd time)', detail: 'Subject: "Momentum Media case study"', time: '10:30 AM', date: 'Today' },
      { id: 't3', type: 'linkedin', title: 'Viewed LinkedIn Profile', detail: 'David viewed your profile', time: '4:00 PM', date: 'Yesterday' },
      { id: 't4', type: 'email', title: 'Initial outreach sent', detail: 'Cold email with personalized value prop', time: '9:00 AM', date: 'Yesterday' },
      { id: 't5', type: 'enrichment', title: 'Lead enriched', detail: 'Siege Waterfall Tier 4 complete', time: '2:00 PM', date: 'Feb 10, 2026' },
    ],
    siegeWaterfall: [
      { tier: 1, name: 'ABN Lookup', status: 'complete', source: 'ABR', timestamp: '4 days ago' },
      { tier: 2, name: 'GMB Enrichment', status: 'complete', source: 'Google', timestamp: '4 days ago' },
      { tier: 3, name: 'Email Discovery', status: 'complete', source: 'Hunter.io', timestamp: '3 days ago' },
      { tier: 4, name: 'LinkedIn Profile', status: 'complete', source: 'LinkedIn', timestamp: '3 days ago' },
      { tier: 5, name: 'Deep Intel', status: 'in-progress', source: 'DataForSEO', timestamp: 'Running...' },
    ],
    notes: [
      { id: 'n1', text: 'Managing Director of mid-size media company. Good budget potential.', author: 'Demo User', date: 'Today, 11:30 AM' },
    ],
  },
};

// ============================================
// 3 DEMO CAMPAIGNS
// ============================================

export const demoCampaigns: DemoCampaign[] = [
  {
    id: 'camp-001',
    name: 'Q1 Dental Practices Blitz',
    status: 'active',
    isAI: true,
    channels: ['email', 'linkedin', 'voice', 'sms'],
    dateRange: 'Jan 15 — Mar 31, 2026',
    leadsEnrolled: 847,
    metrics: {
      meetings: 12,
      replyRate: '3.8%',
      openRate: '61%',
      showRate: '85%',
      avgALS: 72,
    },
    sequence: [
      { step: 1, channel: 'email', day: 0, title: 'Personalized intro with dental practice pain points', sent: 847, opened: 516, replied: 32, status: 'completed' },
      { step: 2, channel: 'linkedin', day: 1, title: 'Connection request with personalized note', sent: 823, replied: 31, status: 'completed' },
      { step: 3, channel: 'email', day: 3, title: 'Case study follow-up — Melbourne dental clinic success', sent: 792, opened: 312, replied: 28, status: 'completed' },
      { step: 4, channel: 'voice', day: 5, title: 'AI call to engaged leads (opened 2+ times)', sent: 67, status: 'active' },
      { step: 5, channel: 'sms', day: 6, title: 'Quick check-in for hot leads only', sent: 0, status: 'pending' },
      { step: 6, channel: 'email', day: 10, title: 'Break-up email — final touch', sent: 0, status: 'pending' },
    ],
  },
  {
    id: 'camp-002',
    name: 'SaaS Founders Outreach',
    status: 'draft',
    isAI: true,
    channels: ['email', 'linkedin'],
    dateRange: 'Draft — Not Started',
    leadsEnrolled: 0,
    metrics: {
      meetings: 0,
      replyRate: '0%',
      openRate: '0%',
      showRate: '0%',
      avgALS: 0,
    },
    sequence: [
      { step: 1, channel: 'email', day: 0, title: 'Personalized intro mentioning Series A/B', sent: 0, status: 'pending' },
      { step: 2, channel: 'linkedin', day: 2, title: 'Connection with mutual interests', sent: 0, status: 'pending' },
      { step: 3, channel: 'email', day: 5, title: 'Case study from similar SaaS company', sent: 0, status: 'pending' },
    ],
  },
  {
    id: 'camp-003',
    name: 'Melbourne Tradies December',
    status: 'completed',
    isAI: false,
    channels: ['email', 'sms', 'voice'],
    dateRange: 'Dec 1 — Dec 31, 2025',
    leadsEnrolled: 523,
    metrics: {
      meetings: 18,
      replyRate: '5.2%',
      openRate: '58%',
      showRate: '78%',
      avgALS: 68,
    },
    sequence: [
      { step: 1, channel: 'email', day: 0, title: 'Holiday season offer for tradies', sent: 523, opened: 303, replied: 27, status: 'completed' },
      { step: 2, channel: 'sms', day: 2, title: 'Quick follow-up SMS', sent: 496, replied: 42, status: 'completed' },
      { step: 3, channel: 'voice', day: 4, title: 'Voice outreach to engaged leads', sent: 128, status: 'completed' },
      { step: 4, channel: 'email', day: 7, title: 'Final offer before holidays', sent: 450, opened: 198, replied: 15, status: 'completed' },
    ],
  },
];

// ============================================
// INBOX MESSAGES (10)
// ============================================

export const demoInboxMessages: DemoInboxMessage[] = [
  {
    id: 'inbox-001',
    name: 'Sarah Chen',
    initials: 'SC',
    company: 'Bloom Digital Melbourne',
    title: 'CEO',
    email: 'sarah@bloomdigital.com.au',
    phone: '+61 412 345 678',
    score: 94,
    tier: 'hot',
    channel: 'email',
    intent: 'meeting',
    sentiment: 'positive',
    preview: "Yes, I'd be interested in learning more. Can we schedule a call next week? We're currently doing about $40K MRR...",
    unread: true,
    timestamp: '2h ago',
    campaignName: 'Q1 Dental Practices Blitz',
  },
  {
    id: 'inbox-002',
    name: 'Marcus Webb',
    initials: 'MW',
    company: 'GrowthLabs Sydney',
    title: 'Founder',
    email: 'marcus@growthlabs.com.au',
    phone: '+61 421 987 654',
    score: 91,
    tier: 'hot',
    channel: 'sms',
    intent: 'meeting',
    sentiment: 'positive',
    preview: "Sure, how about Thursday? I've got 30 mins around 2pm if that works for you.",
    unread: true,
    timestamp: '3h ago',
    campaignName: 'Q1 Dental Practices Blitz',
  },
  {
    id: 'inbox-003',
    name: 'David Park',
    initials: 'DP',
    company: 'Momentum Media',
    title: 'Managing Director',
    email: 'david@momentummedia.com.au',
    score: 89,
    tier: 'hot',
    channel: 'email',
    intent: 'interested',
    sentiment: 'positive',
    preview: 'Interesting approach. Can you send more information about pricing and how this works for agencies our size?',
    unread: true,
    timestamp: '5h ago',
    campaignName: 'Q1 Dental Practices Blitz',
  },
  {
    id: 'inbox-004',
    name: 'Lisa Wong',
    initials: 'LW',
    company: 'Pixel Perfect Agency',
    title: 'Founder & CEO',
    email: 'lisa@pixelperfect.com.au',
    score: 85,
    tier: 'hot',
    channel: 'linkedin',
    intent: 'question',
    sentiment: 'positive',
    preview: 'Thanks for reaching out! Your approach is interesting. How does the AI calling work exactly?',
    unread: true,
    timestamp: '1d ago',
    campaignName: 'Q1 Dental Practices Blitz',
  },
  {
    id: 'inbox-005',
    name: 'James Cooper',
    initials: 'JC',
    company: 'Cooper Electrical Services',
    title: 'Owner',
    email: 'james@cooperelectrical.com.au',
    phone: '+61 433 222 333',
    score: 82,
    tier: 'warm',
    channel: 'sms',
    intent: 'interested',
    sentiment: 'positive',
    preview: "Hey! Yeah we've been looking for something like this. What's the typical cost?",
    unread: true,
    timestamp: '1d ago',
    campaignName: 'Melbourne Tradies December',
  },
  {
    id: 'inbox-006',
    name: 'Anna Smith',
    initials: 'AS',
    company: 'Digital First Agency',
    title: 'Marketing Director',
    email: 'anna@digitalfirst.com.au',
    score: 70,
    tier: 'warm',
    channel: 'email',
    intent: 'later',
    sentiment: 'neutral',
    preview: "Thanks for reaching out. We're evaluating solutions for Q2. Can you follow up in March?",
    unread: false,
    timestamp: '2d ago',
    campaignName: 'Q1 Dental Practices Blitz',
  },
  {
    id: 'inbox-007',
    name: 'Tom Brown',
    initials: 'TB',
    company: 'Scale Trades Australia',
    title: 'Director',
    email: 'tom@scaletrades.com.au',
    score: 76,
    tier: 'warm',
    channel: 'email',
    intent: 'question',
    sentiment: 'neutral',
    preview: 'How do you compare to other lead gen services? We tried Apollo before and it was hit or miss.',
    unread: false,
    timestamp: '3d ago',
    campaignName: 'Melbourne Tradies December',
  },
  {
    id: 'inbox-008',
    name: 'Daniel Lee',
    initials: 'DL',
    company: 'Spark Creative',
    title: 'Marketing Manager',
    email: 'daniel@sparkcreative.com.au',
    score: 58,
    tier: 'cool',
    channel: 'email',
    intent: 'objection',
    sentiment: 'negative',
    preview: 'Not interested at this time. Please remove me from your list.',
    unread: false,
    timestamp: '4d ago',
    campaignName: 'Q1 Dental Practices Blitz',
  },
  {
    id: 'inbox-009',
    name: 'Rachel Nguyen',
    initials: 'RN',
    company: 'Growth Dental Kew',
    title: 'Practice Manager',
    email: 'rachel@growthdentalkew.com.au',
    score: 74,
    tier: 'warm',
    channel: 'email',
    intent: 'meeting',
    sentiment: 'positive',
    preview: "This sounds perfect for us. I'll need to loop in Dr. Nguyen. Can we do a call next Tuesday?",
    unread: false,
    timestamp: '5d ago',
    campaignName: 'Q1 Dental Practices Blitz',
  },
  {
    id: 'inbox-010',
    name: 'Chris Anderson',
    initials: 'CA',
    company: 'Anderson Accounting',
    title: 'Managing Partner',
    email: 'chris@andersonaccounting.com.au',
    score: 72,
    tier: 'warm',
    channel: 'linkedin',
    intent: 'interested',
    sentiment: 'positive',
    preview: 'Good timing actually. We just lost our marketing person and need help with lead gen. Tell me more.',
    unread: false,
    timestamp: '1w ago',
    campaignName: 'Q1 Dental Practices Blitz',
  },
];

// ============================================
// 30 DAYS OF REPORT METRICS
// ============================================

export const demoReportMetrics = {
  heroMetrics: [
    { id: 'meetings', label: 'Meetings Booked', value: 52, change: 23, changeLabel: 'vs last period', accentColor: 'amber' },
    { id: 'pipeline', label: 'Pipeline Generated', value: 221, suffix: 'K', prefix: '$', change: 31, changeLabel: 'vs last period', accentColor: 'teal' },
    { id: 'showRate', label: 'Show Rate', value: 68, suffix: '%', change: 5, changeLabel: 'above benchmark', accentColor: 'blue' },
    { id: 'roi', label: 'Return on Investment', value: 8.2, suffix: 'x', change: 1.4, changeLabel: 'vs last quarter', accentColor: 'green' },
  ],
  channelData: [
    { channel: 'email' as Channel, name: 'Email', volume: 3420, volumeLabel: 'Sent', replyRate: 4.6, meetings: 18 },
    { channel: 'linkedin' as Channel, name: 'LinkedIn', volume: 890, volumeLabel: 'Requests', replyRate: 7.5, meetings: 12 },
    { channel: 'sms' as Channel, name: 'SMS', volume: 520, volumeLabel: 'Sent', replyRate: 27.3, meetings: 8 },
    { channel: 'voice' as Channel, name: 'Voice AI', volume: 180, volumeLabel: 'Calls', replyRate: 23.3, meetings: 11 },
    { channel: 'mail' as Channel, name: 'Direct Mail', volume: 45, volumeLabel: 'Sent', replyRate: 6.7, meetings: 3 },
  ],
  meetingsData: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(Date.now() - (29 - i) * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    value: Math.floor(Math.random() * 4) + 1,
  })),
  funnelData: [
    { stage: 'contacted', label: 'Contacted', count: 5055, description: 'Total Touches', percentage: 100 },
    { stage: 'engaged', label: 'Engaged', count: 2123, description: 'Opens/Views', percentage: 42 },
    { stage: 'replied', label: 'Replied', count: 404, description: 'Positive', percentage: 8 },
    { stage: 'booked', label: 'Booked', count: 52, description: 'Meetings', percentage: 1 },
  ],
  tierData: [
    { tier: 'hot' as LeadTier, count: 312, conversionRate: 8.7 },
    { tier: 'warm' as LeadTier, count: 589, conversionRate: 3.2 },
    { tier: 'cool' as LeadTier, count: 234, conversionRate: 1.1 },
    { tier: 'cold' as LeadTier, count: 167, conversionRate: 0.4 },
  ],
  roiSummary: {
    spend: 27000,
    pipeline: 221000,
    roi: 8.2,
  },
};

// ============================================
// DASHBOARD DATA
// ============================================

export const demoDashboardData = {
  meetingsHero: {
    current: 12,
    target: 10,
    goalText: 'Target exceeded — 3 days early',
    trendPercent: 25,
    trendLabel: 'vs last month',
  },
  channelOrchestration: {
    totalTouches: 1800,
    channels: [
      { id: 'email', label: 'Email', value: 847, color: 'accent-primary' },
      { id: 'linkedin', label: 'LinkedIn', value: 423, color: 'accent-blue' },
      { id: 'sms', label: 'SMS', value: 127, color: 'accent-teal' },
      { id: 'voice', label: 'Calls', value: 47, color: 'status-warning' },
      { id: 'mail', label: 'Mail', value: 23, color: 'amber-light' },
    ],
  },
  statsGrid: [
    { id: 'show-rate', value: '68%', label: 'Show Rate', change: '↑ 5% vs avg', positive: true },
    { id: 'deals', value: '4', label: 'Deals Started', change: '↑ 2 this week', positive: true },
    { id: 'pipeline', value: '$47K', label: 'Pipeline Value', change: '↑ $12K added', positive: true },
    { id: 'roi', value: '8.2x', label: 'ROI', change: 'Lifetime', positive: null },
  ],
  hotProspects: demoLeads.filter(l => l.tier === 'hot').slice(0, 3).map(l => ({
    id: l.id,
    initials: l.name.split(' ').map(n => n[0]).join(''),
    name: l.name,
    company: l.company,
    title: l.title,
    score: l.alsScore,
    tier: l.tier,
    badges: l.whyHot.slice(0, 2).map(w => ({ label: w.toUpperCase(), variant: 'hot' as const })),
  })),
  voiceStats: {
    calls: 47,
    connected: 31,
    booked: 8,
    rate: '26%',
  },
  recentCalls: [
    { id: '1', name: 'Sarah Chen', outcome: 'BOOKED' as const, summary: '"Interested in learning more"', duration: '3:12' },
    { id: '2', name: 'Marcus Webb', outcome: 'BOOKED' as const, summary: '"Let\'s do Thursday"', duration: '4:12' },
  ],
  insights: {
    whoConverts: [
      { label: 'CEO/Founder', value: '2.3x ↑' },
      { label: 'Marketing Dir', value: '1.8x ↑' },
    ],
    bestChannelMix: [
      { label: 'Email → LinkedIn', value: '68%' },
      { label: '+Voice', value: '+41%' },
    ],
    discovery: 'Prospects are most responsive on Tuesdays. Pipeline momentum is strongest mid-week.',
  },
  activityFeed: [
    { id: '1', type: 'email' as const, text: 'Sarah Chen opened your email', subtext: '(5th time)', time: '2 minutes ago', status: 'success' as const },
    { id: '2', type: 'linkedin' as const, text: 'Marcus Webb visited pricing page', time: '15 minutes ago', status: 'info' as const },
    { id: '3', type: 'linkedin' as const, text: 'David Park replied on LinkedIn', time: '1 hour ago', status: 'warning' as const },
    { id: '4', type: 'meeting' as const, text: 'Meeting booked with Sarah via call', time: '2 hours ago', status: 'success' as const },
  ],
  weekAhead: [
    { id: '1', datetime: 'Today 2:00 PM', type: 'Discovery Call', contact: 'Sarah Chen', company: 'Bloom Digital', dealValue: '$8K', status: 'success' as const },
    { id: '2', datetime: 'Thursday 10:00 AM', type: 'Demo Call', contact: 'Marcus Webb', company: 'GrowthLabs', dealValue: '$15K', status: 'info' as const },
    { id: '3', datetime: 'Friday 3:30 PM', type: 'Intro Call', contact: 'David Park', company: 'Momentum Media', status: 'info' as const },
  ],
  warmReplies: demoInboxMessages.filter(m => m.sentiment === 'positive').slice(0, 3).map(m => ({
    id: m.id,
    quote: m.preview.slice(0, 60) + '...',
    contact: m.name,
    company: m.company,
    time: m.timestamp,
  })),
};

// ============================================
// SETTINGS DATA
// ============================================

export const demoSettingsData = {
  userProfile: demoAgencyProfile,
  teamMembers: [
    { id: '1', name: 'Demo User', email: 'demo@horizondigital.com.au', role: 'owner' as const, initials: 'DU' },
    { id: '2', name: 'Jane Miller', email: 'jane@horizondigital.com.au', role: 'admin' as const, initials: 'JM' },
    { id: '3', name: 'Tom Smith', email: 'tom@horizondigital.com.au', role: 'member' as const, initials: 'TS' },
  ],
  integrations: [
    { id: '1', name: 'Resend', icon: 'email' as const, status: 'connected' as const, description: 'Email delivery' },
    { id: '2', name: 'LinkedIn', icon: 'linkedin' as const, status: 'connected' as const, description: 'Via HeyReach' },
    { id: '3', name: 'Twilio', icon: 'sms' as const, status: 'connected' as const, description: 'SMS messaging' },
    { id: '4', name: 'Voice AI', icon: 'voice' as const, status: 'connected' as const, description: 'Call automation' },
    { id: '5', name: 'Google Calendar', icon: 'calendar' as const, status: 'connected' as const, description: 'Scheduling' },
    { id: '6', name: 'Apollo', icon: 'crm' as const, status: 'connected' as const, description: 'Lead enrichment' },
  ],
  notifications: [
    { id: '1', label: 'Email Notifications', description: 'Receive email alerts for important activity', enabled: true },
    { id: '2', label: 'New Reply Alerts', description: 'Get notified when leads respond', enabled: true },
    { id: '3', label: 'Meeting Booked', description: 'Get notified when a meeting is scheduled', enabled: true },
    { id: '4', label: 'Hot Lead Alerts', description: 'Instant notification when a lead becomes hot', enabled: true },
    { id: '5', label: 'Weekly Digest', description: "Summary of your week's performance", enabled: true },
    { id: '6', label: 'Marketing Updates', description: 'News about new features and updates', enabled: false },
  ],
  apiKeys: [
    { id: '1', name: 'Production API Key', value: 'aos_live_demo_••••••••••••', type: 'production' as const },
    { id: '2', name: 'Test API Key', value: 'aos_test_demo_••••••••••••', type: 'test' as const },
  ],
  billingInfo: {
    plan: 'Ignition',
    price: '$199',
    period: 'month',
    nextBilling: 'March 15, 2026',
    usage: {
      leads: { used: 847, limit: 2000 },
      emails: { used: 3420, limit: 10000 },
      campaigns: { used: 3, limit: 10 },
    },
  },
};
