-- Migration 072: Add missing columns across all tables
-- Bug #13 fix + full column audit
-- Generated by CEO Directive #101

-- =====================================================
-- CAMPAIGNS TABLE (Bug #13 - pause columns)
-- =====================================================

-- paused_at: When the campaign was paused
ALTER TABLE campaigns 
ADD COLUMN IF NOT EXISTS paused_at TIMESTAMP WITH TIME ZONE;

-- pause_reason: Why the campaign was paused
ALTER TABLE campaigns 
ADD COLUMN IF NOT EXISTS pause_reason TEXT;

-- paused_by_user_id: Who paused the campaign
ALTER TABLE campaigns 
ADD COLUMN IF NOT EXISTS paused_by_user_id UUID REFERENCES users(id);

-- uses_default_sequence: Whether campaign uses default sequence
ALTER TABLE campaigns 
ADD COLUMN IF NOT EXISTS uses_default_sequence BOOLEAN DEFAULT TRUE;

-- =====================================================
-- CAMPAIGN_SEQUENCES TABLE
-- =====================================================

-- purpose: The purpose/goal of this sequence step
ALTER TABLE campaign_sequences 
ADD COLUMN IF NOT EXISTS purpose TEXT;

-- skip_if: Condition to skip this step (JSON or expression)
ALTER TABLE campaign_sequences 
ADD COLUMN IF NOT EXISTS skip_if TEXT;

-- =====================================================
-- PERSONAS TABLE
-- =====================================================

-- suggested_domains: Suggested email domains for this persona
ALTER TABLE personas 
ADD COLUMN IF NOT EXISTS suggested_domains TEXT;

-- =====================================================
-- Comments
-- =====================================================

COMMENT ON COLUMN campaigns.paused_at IS 'Timestamp when campaign was paused';
COMMENT ON COLUMN campaigns.pause_reason IS 'Reason the campaign was paused';
COMMENT ON COLUMN campaigns.paused_by_user_id IS 'User who paused the campaign';
COMMENT ON COLUMN campaigns.uses_default_sequence IS 'Whether this campaign uses the default sequence template';

COMMENT ON COLUMN campaign_sequences.purpose IS 'Purpose/goal of this sequence step';
COMMENT ON COLUMN campaign_sequences.skip_if IS 'Condition expression to skip this step';

COMMENT ON COLUMN personas.suggested_domains IS 'Suggested email domains for this persona';
